/* Lektion 2 — Wortschatz. (Abschnitt D „Mein Kurzvortrag“ = Redemittel, keine Vokabelkarten) */
window.DECK = window.DECK || { lessons: {} };
window.DECK.lessons[2] = {
  title: "Leben in Großstädten",
  subtitle: "Stadt, Stadtgrün & Umbau",
  cards: [
    // A — Leben in Großstädten
    { w:"Architektur", a:"die", pl:"-en", g:"Pl. selten", pos:"n", en:"architecture", de:"die Kunst, Gebäude zu planen und zu bauen", s:"Die moderne Architektur der Stadt beeindruckt viele Touristen.", sec:"A" },
    { w:"Architekt", a:"der", pl:"-en", pos:"n", en:"architect (m)", de:"eine Person, die Gebäude plant", s:"Der Architekt stellte seinen Entwurf für das Museum vor.", sec:"A" },
    { w:"Architektin", a:"die", pl:"-nen", pos:"n", en:"architect (f)", de:"eine Frau, die Gebäude plant", s:"Die Architektin gewann den Wettbewerb für das Hochhaus.", sec:"A" },
    { w:"Stadtplanung", a:"die", pl:"-en", pos:"n", en:"urban planning", de:"das Planen, wie eine Stadt gebaut und organisiert wird", s:"Gute Stadtplanung sorgt für genug Grünflächen.", sec:"A" },
    { w:"Hochhaus", a:"das", pl:"¨er", pos:"n", en:"high-rise", de:"ein sehr hohes Wohn- oder Bürogebäude", s:"In diesem Hochhaus gibt es über dreißig Etagen.", sec:"A" },
    { w:"Wolkenkratzer", a:"der", pl:"-", pos:"n", en:"skyscraper", de:"ein extrem hohes Hochhaus", s:"Von dem Wolkenkratzer hat man einen tollen Blick über die Stadt.", sec:"A" },
    { w:"Skyline", a:"die", pl:"-s", pos:"n", en:"skyline", de:"die Silhouette einer Stadt mit ihren hohen Gebäuden", s:"Die Skyline von Frankfurt ist berühmt.", sec:"A" },
    { w:"Altstadt", a:"die", pl:"¨e", pos:"n", en:"old town", de:"der alte, historische Teil einer Stadt", s:"In der Altstadt stehen viele Häuser aus dem Mittelalter.", sec:"A" },
    { w:"historisch", a:"", g:"≠ modern", pos:"adj", en:"historic(al)", de:"aus der Geschichte, alt und bedeutend", s:"Das historische Rathaus wird gerade renoviert.", sec:"A" },
    { w:"Run", a:"der", pl:"-s", pos:"n", en:"rush, run (on sth)", de:"ein großer Andrang auf etwas", s:"Der Run auf günstige Wohnungen ist enorm.", sec:"A", c:"der Run auf + A" },
    { w:"Verstädterung", a:"die", pl:"-en", g:"Pl. selten", pos:"n", en:"urbanization", de:"das Wachsen der Städte, wenn immer mehr Menschen dort leben", s:"Die Verstädterung nimmt weltweit zu.", sec:"A" },
    { w:"Landflucht", a:"die", pl:"-en", g:"Pl. selten", pos:"n", en:"rural exodus", de:"das Wegziehen der Menschen vom Land in die Stadt", s:"Die Landflucht lässt viele Dörfer schrumpfen.", sec:"A" },
    { w:"Prognose", a:"die", pl:"-n", pos:"n", en:"forecast", de:"eine Vorhersage über die Zukunft", s:"Die Prognose sagt weiteres Wachstum der Städte voraus.", sec:"A" },
    { w:"prognostizieren", a:"", pos:"v", en:"to forecast", de:"die Zukunft vorhersagen", s:"Experten prognostizieren steigende Mieten.", sec:"A" },
    { w:"weltweit", a:"", pos:"adj", en:"worldwide", de:"auf der ganzen Welt", s:"Weltweit ziehen Menschen in die Städte.", sec:"A" },
    { w:"Anteil", a:"der", pl:"-e", pos:"n", en:"share, proportion", de:"ein Teil von einem Ganzen", s:"Der Anteil der Stadtbewohner steigt ständig.", sec:"A" },
    { w:"verdoppeln", a:"", pos:"v", en:"to double", de:"doppelt so groß machen", s:"Die Einwohnerzahl hat sich in zwanzig Jahren verdoppelt.", sec:"A" },
    { w:"Attraktivität", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"attractiveness", de:"die Eigenschaft, anziehend zu sein", s:"Die Attraktivität der Stadt zieht junge Leute an.", sec:"A" },
    { w:"attraktiv", a:"", pos:"adj", en:"attractive", de:"anziehend, reizvoll", s:"Berlin ist für Künstler sehr attraktiv.", sec:"A" },
    { w:"anregend", a:"", pos:"adj", en:"stimulating", de:"so, dass es Interesse und Ideen weckt", s:"Das Stadtleben ist anregend und abwechslungsreich.", sec:"A" },
    { w:"Image", a:"das", pl:"-s", pos:"n", en:"image, reputation", de:"das Bild, das andere von jemandem oder etwas haben", s:"Die Stadt arbeitet an einem moderneren Image.", sec:"A" },
    { w:"cool", a:"", pos:"adj", en:"cool", de:"(umgangssprachlich) toll, lässig", s:"Das neue Viertel gilt als besonders cool.", sec:"A" },
    { w:"Bildungseinrichtung", a:"die", pl:"-en", pos:"n", en:"educational institution", de:"ein Ort zum Lernen, z. B. Schule oder Universität", s:"Die Stadt hat viele Bildungseinrichtungen.", sec:"A" },
    { w:"Arbeitsstelle", a:"die", pl:"-n", pos:"n", en:"job, position", de:"ein Platz, an dem man arbeitet", s:"In der Großstadt findet man leichter eine Arbeitsstelle.", sec:"A" },
    { w:"Startup", a:"das", pl:"-s", pos:"n", en:"startup", de:"ein junges, neu gegründetes Unternehmen", s:"Sie hat mit Freunden ein Startup gegründet.", sec:"A", c:"ein Startup gründen" },
    { w:"Umfrage", a:"die", pl:"-n", pos:"n", en:"survey", de:"eine Befragung vieler Menschen zu einem Thema", s:"Eine Umfrage zeigt, dass viele aufs Land ziehen wollen.", sec:"A" },
    { w:"Faktor", a:"der", pl:"-en", pos:"n", en:"factor", de:"ein Punkt, der etwas beeinflusst", s:"Die Miete ist ein wichtiger Faktor bei der Wohnungssuche.", sec:"A", c:"Stressfaktor" },
    { w:"Lärm", a:"der", pl:"—", g:"nur Sg.", pos:"n", en:"noise", de:"laute, störende Geräusche", s:"Der Lärm in der Innenstadt stört mich beim Schlafen.", sec:"A", c:"Verkehrslärm" },
    { w:"Verschmutzung", a:"die", pl:"-en", pos:"n", en:"pollution", de:"das Schmutzigmachen der Umwelt", s:"Die Verschmutzung der Luft ist in Großstädten ein Problem.", sec:"A", c:"Umweltverschmutzung" },
    { w:"Smog", a:"der", pl:"", pos:"n", en:"smog", de:"eine Mischung aus Nebel und Abgasen über einer Stadt", s:"An heißen Tagen liegt Smog über der Stadt.", sec:"A" },
    { w:"Abgas", a:"das", pl:"-e", g:"meist Pl.", pos:"n", en:"exhaust gas", de:"das giftige Gas, das Autos ausstoßen", s:"Die Abgase der Autos schaden der Gesundheit.", sec:"A", c:"die Autoabgase" },
    { w:"schädigen", a:"", pos:"v", en:"to damage, to harm", de:"etwas kaputt oder schlechter machen", s:"Rauchen schädigt die Gesundheit.", sec:"A", c:"die Gesundheit schädigen" },
    { w:"Viertel", a:"das", pl:"-", pos:"n", en:"district, quarter", de:"ein Teil einer Stadt", s:"Ich wohne in einem ruhigen Viertel.", sec:"A", c:"das Stadtviertel" },
    { w:"blicken", a:"", pos:"v", en:"to look, to gaze", de:"in eine Richtung schauen", s:"Wir blicken optimistisch in die Zukunft.", sec:"A", c:"in die Zukunft blicken" },
    { w:"Technologie", a:"die", pl:"-n", pos:"n", en:"technology", de:"die Anwendung von technischem Wissen", s:"Neue Technologien verändern die Städte.", sec:"A" },
    { w:"Technologiefirma", a:"die", pl:"-firmen", pos:"n", en:"technology company", de:"ein Unternehmen, das mit Technik arbeitet", s:"Viele Technologiefirmen siedeln sich in der Stadt an.", sec:"A" },
    { w:"Digitalisierung", a:"die", pl:"—", g:"hier nur Sg.", pos:"n", en:"digitalization", de:"die Umstellung auf digitale Technik", s:"Die Digitalisierung verändert unsere Arbeit.", sec:"A" },
    { w:"digital", a:"", pos:"adj", en:"digital", de:"mit Computern und elektronischen Daten", s:"Viele Dienste sind heute komplett digital.", sec:"A" },
    { w:"vernetzen", a:"", pos:"v", en:"to network, to connect", de:"Dinge oder Menschen miteinander verbinden", s:"Moderne Städte vernetzen ihre Verkehrssysteme.", sec:"A" },
    { w:"Workshop", a:"der", pl:"-s", pos:"n", en:"workshop", de:"eine kurze, praktische Arbeitsveranstaltung", s:"Im Workshop entwickeln wir neue Ideen.", sec:"A" },
    { w:"innovativ", a:"", pos:"adj", en:"innovative", de:"mit neuen Ideen, erneuernd", s:"Die Firma sucht innovative Lösungen.", sec:"A" },
    { w:"lebenswert", a:"", pos:"adj", en:"worth living in", de:"so, dass man dort gern und gut lebt", s:"Grüne Städte sind lebenswerter.", sec:"A" },
    { w:"Konzept", a:"das", pl:"-e", pos:"n", en:"concept", de:"ein durchdachter Plan", s:"Wir erarbeiten ein Konzept für den neuen Park.", sec:"A", c:"ein Konzept erarbeiten" },
    { w:"gründen", a:"", pos:"v", en:"to found, to establish", de:"etwas Neues ins Leben rufen", s:"Sie wollen eine eigene Firma gründen.", sec:"A" },
    // B — Städte werden grün
    { w:"anbauen", a:"", pos:"v", en:"to grow, to cultivate", de:"Pflanzen ziehen und wachsen lassen", s:"In der Stadt kann man Gemüse auf dem Dach anbauen.", sec:"B", c:"Gemüse / Obst / Getreide anbauen" },
    { w:"Anbau", a:"der", pl:"—", g:"nur Sg.", pos:"n", en:"cultivation, growing", de:"das Anbauen von Pflanzen", s:"Der Anbau von Gemüse in der Stadt wird beliebter.", sec:"B" },
    { w:"versorgen", a:"", pos:"v", en:"to supply, to provide", de:"jemandem geben, was er braucht", s:"Ein Dachgarten kann viele Familien mit Gemüse versorgen.", sec:"B", c:"jdn. versorgen mit + D" },
    { w:"Landschaft", a:"die", pl:"-en", pos:"n", en:"landscape", de:"ein Gebiet der Natur, so wie es aussieht", s:"Rund um die Stadt liegt eine grüne Landschaft.", sec:"B" },
    { w:"Landwirtschaft", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"agriculture", de:"das Anbauen von Pflanzen und Halten von Tieren", s:"Die Landwirtschaft versorgt die Städte mit Lebensmitteln.", sec:"B" },
    { w:"landwirtschaftlich", a:"", pos:"adj", en:"agricultural", de:"zur Landwirtschaft gehörend", s:"Sie verkaufen landwirtschaftliche Produkte direkt vom Hof.", sec:"B", c:"landwirtschaftliche Produkte" },
    { w:"vertikal", a:"", pos:"adj", en:"vertical", de:"senkrecht, von unten nach oben", s:"Vertikale Gärten wachsen an Hauswänden.", sec:"B" },
    { w:"beitragen", a:"", pos:"v", en:"to contribute", de:"mithelfen, dass etwas gelingt", s:"Stadtgärten tragen zu einer besseren Luft bei.", sec:"B", c:"zu einer Lösung beitragen" },
    { w:"Etage", a:"die", pl:"-n", pos:"n", en:"floor, storey", de:"ein Stockwerk in einem Gebäude", s:"Das Café liegt in der obersten Etage.", sec:"B" },
    { w:"-stöckig", a:"", pos:"adj", en:"-storey (e.g. 2-storey)", de:"mit einer bestimmten Zahl an Stockwerken", s:"Sie wohnen in einem dreistöckigen Haus.", sec:"B", c:"2-stöckig, 3-stöckig …" },
    { w:"preisgünstig", a:"", pos:"adj", en:"cheap, good value", de:"nicht teuer, mit gutem Preis", s:"Das Gemüse vom Dach ist frisch und preisgünstig.", sec:"B" },
    { w:"Fläche", a:"die", pl:"-n", pos:"n", en:"area, surface", de:"ein flaches Stück Boden oder Raum", s:"Auf dieser Fläche entsteht ein neuer Park.", sec:"B" },
    { w:"Fußballfeld", a:"das", pl:"-er", pos:"n", en:"football field", de:"der Platz, auf dem Fußball gespielt wird", s:"Der Dachgarten ist so groß wie ein Fußballfeld.", sec:"B" },
    { w:"Ersatz", a:"der", pl:"—", g:"nur Sg.", pos:"n", en:"replacement, substitute", de:"etwas, das an die Stelle von etwas anderem tritt", s:"Lampen dienen als Ersatz für das Sonnenlicht.", sec:"B", c:"elektrisches Licht als Ersatz für Sonnenlicht" },
    { w:"Sonnenlicht", a:"das", pl:"—", g:"nur Sg.", pos:"n", en:"sunlight", de:"das Licht der Sonne", s:"Pflanzen brauchen Sonnenlicht zum Wachsen.", sec:"B" },
    { w:"beleuchten", a:"", pos:"v", en:"to illuminate, to light up", de:"Licht auf etwas richten, hell machen", s:"Spezielle Lampen beleuchten die Pflanzen.", sec:"B" },
    { w:"Beleuchtung", a:"die", pl:"-en", pos:"n", en:"lighting", de:"das Licht bzw. die Lampen an einem Ort", s:"Die Beleuchtung im Innenhof ist warm und angenehm.", sec:"B" },
    { w:"urban", a:"", pos:"adj", en:"urban", de:"zur Stadt gehörend, städtisch", s:"Urbane Gärten liegen mitten in der Stadt.", sec:"B" },
    { w:"Trend", a:"der", pl:"-s", pos:"n", en:"trend", de:"eine Entwicklung, der viele folgen", s:"Stadtgärtnern ist ein wachsender Trend.", sec:"B", c:"sich einem Trend anschließen" },
    { w:"gärtnern", a:"", pos:"v", en:"to garden", de:"im Garten arbeiten, Pflanzen pflegen", s:"Am Wochenende gärtnere ich auf dem Balkon.", sec:"B" },
    { w:"begrünen", a:"", pos:"v", en:"to plant with greenery", de:"mit Pflanzen bedecken, grün machen", s:"Die Stadt will viele Dächer begrünen.", sec:"B" },
    { w:"pflanzen", a:"", pos:"v", en:"to plant", de:"eine Pflanze in die Erde setzen", s:"Wir pflanzen im Frühling Tomaten.", sec:"B" },
    { w:"Pflanze", a:"die", pl:"-n", pos:"n", en:"plant", de:"ein Lebewesen wie Blume, Baum oder Gras", s:"Diese Pflanze braucht wenig Wasser.", sec:"B" },
    { w:"säen", a:"", pos:"v", en:"to sow", de:"Samen in die Erde bringen", s:"Im März säen wir die ersten Kräuter.", sec:"B" },
    { w:"Samen", a:"der", pl:"-", pos:"n", en:"seed", de:"das kleine Korn, aus dem eine Pflanze wächst", s:"Aus diesem Samen wird eine Sonnenblume.", sec:"B" },
    { w:"Ernte", a:"die", pl:"-n", pos:"n", en:"harvest", de:"das Einsammeln der reifen Pflanzen", s:"Die Ernte war dieses Jahr besonders gut.", sec:"B" },
    { w:"ernten", a:"", pos:"v", en:"to harvest", de:"reife Pflanzen einsammeln", s:"Im Herbst ernten wir die Äpfel.", sec:"B" },
    { w:"gießen", a:"", pos:"v", en:"to water", de:"Pflanzen Wasser geben", s:"Bei Hitze muss man die Beete täglich gießen.", sec:"B" },
    { w:"genießen", a:"", pos:"v", en:"to enjoy", de:"etwas mit Freude erleben", s:"Ich genieße die Ruhe im grünen Innenhof.", sec:"B" },
    { w:"Wachstum", a:"das", pl:"—", g:"nur Sg.", pos:"n", en:"growth", de:"das Größer- oder Mehr-Werden", s:"Das schnelle Wachstum der Stadt bringt Probleme.", sec:"B" },
    { w:"Parkgarage", a:"die", pl:"-n", pos:"n", en:"parking garage", de:"ein Gebäude zum Parken von Autos", s:"Auf dem Dach der Parkgarage entsteht ein Garten.", sec:"B" },
    { w:"Dachterrasse", a:"die", pl:"-n", pos:"n", en:"roof terrace", de:"ein offener Platz oben auf einem Gebäude", s:"Von der Dachterrasse sieht man die ganze Stadt.", sec:"B" },
    { w:"Innenhof", a:"der", pl:"¨e", pos:"n", en:"inner courtyard", de:"ein offener Platz in der Mitte eines Gebäudes", s:"Die Kinder spielen im Innenhof.", sec:"B" },
    { w:"trist", a:"", pos:"adj", en:"dreary, bleak", de:"grau, langweilig und ohne Freude", s:"Ohne Pflanzen wirkt der Hof trist.", sec:"B" },
    { w:"Biene", a:"die", pl:"-n", pos:"n", en:"bee", de:"ein Insekt, das Honig macht und Blüten bestäubt", s:"Auf dem Dach halten sie sogar Bienen.", sec:"B", c:"Bienen halten" },
    { w:"Vordergrund", a:"der", pl:"¨e", pos:"n", en:"foreground", de:"der vordere, wichtige Teil", s:"Bei diesem Projekt steht die Natur im Vordergrund.", sec:"B", c:"im Vordergrund stehen" },
    { w:"gehen um", a:"", g:"+ A", pos:"phr", en:"to be about", de:"das Thema oder Ziel von etwas sein", s:"Bei Stadtgärten geht es um die Nähe zur Natur.", sec:"B", c:"es geht um die Nähe zur Natur" },
    { w:"brachliegen", a:"", pos:"v", en:"to lie fallow / unused", de:"ungenutzt und leer liegen", s:"Viele Flächen in der Stadt liegen brach.", sec:"B", c:"eine brachliegende Fläche" },
    { w:"bearbeiten", a:"", pos:"v", en:"to work on, to cultivate", de:"an etwas arbeiten; den Boden pflegen", s:"Freiwillige bearbeiten das Beet gemeinsam.", sec:"B" },
    { w:"nutzen", a:"", pos:"v", en:"to use, to make use of", de:"etwas verwenden, um einen Vorteil zu haben", s:"Wir nutzen das Dach als Garten.", sec:"B" },
    { w:"erwerben", a:"", pos:"v", en:"to acquire", de:"etwas kaufen oder bekommen", s:"Der Verein hat die Fläche günstig erworben.", sec:"B" },
    { w:"Bewirtschaftung", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"management, cultivation", de:"das Pflegen und Nutzen von Land", s:"Die Bewirtschaftung des Gartens teilen sich die Nachbarn.", sec:"B" },
    { w:"verwalten", a:"", pos:"v", en:"to manage, to administer", de:"sich um die Organisation von etwas kümmern", s:"Ein Verein verwaltet den Gemeinschaftsgarten.", sec:"B" },
    { w:"jährlich", a:"", pos:"adj", en:"annual, yearly", de:"jedes Jahr, einmal im Jahr", s:"Die jährliche Ernte wird gemeinsam gefeiert.", sec:"B" },
    { w:"Betrag", a:"der", pl:"¨e", pos:"n", en:"amount, sum", de:"eine bestimmte Menge Geld", s:"Jedes Mitglied zahlt einen kleinen Betrag im Jahr.", sec:"B" },
    { w:"austauschen, sich", a:"", pos:"v", en:"to exchange (ideas)", de:"sich gegenseitig Informationen oder Ideen geben", s:"Die Gärtner tauschen sich über Tipps aus.", sec:"B" },
    { w:"gegenseitig helfen, sich", a:"", pos:"phr", en:"to help one another", de:"einer hilft dem anderen", s:"Im Garten helfen sich alle gegenseitig.", sec:"B" },
    { w:"anonym", a:"", pos:"adj", en:"anonymous", de:"ohne dass man den Namen kennt, unbekannt", s:"In großen Städten bleibt man oft anonym.", sec:"B" },
    { w:"Anonymität", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"anonymity", de:"der Zustand, unbekannt zu sein", s:"Gemeinschaftsgärten wirken gegen die Anonymität.", sec:"B" },
    { w:"Mittel", a:"das", pl:"-", pos:"n", en:"means, remedy", de:"etwas, mit dem man ein Ziel erreicht", s:"Ein Garten ist ein gutes Mittel gegen Einsamkeit.", sec:"B", c:"ein Mittel gegen die Anonymität" },
    { w:"Nachbarschaft", a:"die", pl:"-en", g:"Pl. selten", pos:"n", en:"neighborhood", de:"die Menschen, die in der Nähe wohnen", s:"In unserer Nachbarschaft kennt man sich gut.", sec:"B" },
    { w:"aufbauen", a:"", pos:"v", en:"to build up", de:"etwas Schritt für Schritt entstehen lassen", s:"So bauen die Bewohner gute Beziehungen auf.", sec:"B", c:"gute Beziehungen aufbauen" },
    { w:"verringern", a:"", pos:"v", en:"to reduce", de:"weniger oder kleiner machen", s:"Gemeinsame Projekte verringern die Distanz zwischen Nachbarn.", sec:"B" },
    // C — Abreißen oder umbauen?
    { w:"wirken", a:"", pos:"v", en:"to seem, to have an effect", de:"einen bestimmten Eindruck machen", s:"Das Hochhaus wirkt auf mich altmodisch.", sec:"C", c:"Das Hochhaus wirkt (auf mich) altmodisch." },
    { w:"altmodisch", a:"", pos:"adj", en:"old-fashioned", de:"nicht mehr modern, aus der Mode", s:"Die Fassade sieht ziemlich altmodisch aus.", sec:"C" },
    { w:"verschlossen", a:"", pos:"adj", en:"closed, reserved", de:"geschlossen; auch: zurückhaltend gegenüber anderen", s:"Das alte Gebäude wirkt kalt und verschlossen.", sec:"C" },
    { w:"Gebäude", a:"das", pl:"-", pos:"n", en:"building", de:"ein gebautes Haus oder Bauwerk", s:"Das Gebäude aus den 70er-Jahren soll umgebaut werden.", sec:"C" },
    { w:"abreißen", a:"", pos:"v", en:"to demolish", de:"ein Gebäude ganz wegnehmen, zerstören", s:"Man will das alte Kaufhaus abreißen.", sec:"C" },
    { w:"Abriss", a:"der", pl:"", pos:"n", en:"demolition", de:"das Abreißen eines Gebäudes", s:"Gegen den Abriss des Hauses gibt es Proteste.", sec:"C" },
    { w:"Quadratmeter", a:"der", pl:"-", pos:"n", en:"square meter", de:"eine Maßeinheit für Fläche", s:"Die Wohnung hat achtzig Quadratmeter.", sec:"C" },
    { w:"umweltschonend", a:"", pos:"adj", en:"eco-friendly", de:"so, dass es die Umwelt schützt", s:"Ein Umbau ist oft umweltschonender als ein Neubau.", sec:"C" },
    { w:"umbauen", a:"", pos:"v", en:"to convert, to rebuild", de:"ein Gebäude verändern, statt es abzureißen", s:"Sie bauen die alte Fabrik zu Wohnungen um.", sec:"C" },
    { w:"Umbau", a:"der", pl:"-ten", pos:"n", en:"conversion, renovation", de:"das Verändern eines bestehenden Gebäudes", s:"Der Umbau des Bahnhofs dauert zwei Jahre.", sec:"C" },
    { w:"komplett", a:"", pos:"adj", en:"complete(ly)", de:"ganz und gar, vollständig", s:"Das Haus wurde komplett renoviert.", sec:"C" },
    { w:"Fassade", a:"die", pl:"-n", pos:"n", en:"facade", de:"die Vorderseite eines Gebäudes", s:"Die neue Fassade ist aus Glas.", sec:"C" },
    { w:"Ebene", a:"die", pl:"-n", pos:"n", en:"level", de:"eine Stufe oder Fläche auf gleicher Höhe", s:"Auf jeder Ebene gibt es Büros und Cafés.", sec:"C" },
    { w:"horizontal", a:"", pos:"adj", en:"horizontal", de:"waagerecht, parallel zum Boden", s:"Die Balkone verlaufen in horizontalen Linien.", sec:"C" },
    { w:"Panorama", a:"das", pl:"-en", pos:"n", en:"panorama", de:"ein weiter Ausblick in alle Richtungen", s:"Vom Dach hat man ein tolles Panorama.", sec:"C" },
    { w:"wohlfühlen, sich", a:"", pos:"v", en:"to feel comfortable", de:"sich angenehm und zufrieden fühlen", s:"In der neuen Wohnung fühlen wir uns wohl.", sec:"C" },
    { w:"Entwicklung", a:"die", pl:"-en", pos:"n", en:"development", de:"die Veränderung über die Zeit", s:"Die Entwicklung des Viertels ist beeindruckend.", sec:"C", c:"Stadtentwicklung" },
    { w:"Überblick", a:"der", pl:"-e", pos:"n", en:"overview", de:"ein allgemeines Bild vom Ganzen", s:"Die Karte gibt einen Überblick über das Projekt.", sec:"C" },
    { w:"Einleitung", a:"die", pl:"-en", pos:"n", en:"introduction", de:"der erste Teil einer Rede oder eines Textes", s:"In der Einleitung stelle ich das Gebäude kurz vor.", sec:"C" },
    { w:"eingehen auf", a:"", g:"+ A", pos:"v", en:"to address, to go into", de:"etwas genauer besprechen", s:"Im Vortrag gehe ich auf die Vorteile des Umbaus ein.", sec:"C" },
    { w:"kommen zu", a:"", g:"+ D", pos:"v", en:"to come to (a point)", de:"einen Punkt erreichen, zu einem Thema übergehen", s:"Damit komme ich zu meinem letzten Punkt.", sec:"C" }
  ]
};
