/* Lektion 5 — Wortschatz */
window.DECK = window.DECK || { lessons: {} };
window.DECK.lessons[5] = {
  title: "Alle reden über das Wetter",
  subtitle: "Wetter, Meteorologie & Klimawandel",
  cards: [
    // A — Alle reden über das Wetter
    { w:"Wetterdienst", a:"der", pl:"-e", pos:"n", en:"weather service", de:"eine Behörde, die das Wetter beobachtet und vorhersagt", s:"Der Wetterdienst warnt vor schweren Gewittern.", sec:"A" },
    { w:"Vorhersage", a:"die", pl:"-n", pos:"n", en:"forecast", de:"eine Aussage darüber, wie das Wetter wird", s:"Die Vorhersage verspricht Sonne für das Wochenende.", sec:"A", c:"Wettervorhersage, -n" },
    { w:"vorhersagen", a:"", pos:"v", en:"to forecast, to predict", de:"sagen, wie etwas in der Zukunft sein wird", s:"Für morgen wird Regen vorhergesagt.", sec:"A" },
    { w:"Voraussage", a:"die", pl:"-n", pos:"n", en:"prediction", de:"eine Aussage über die Zukunft", s:"Seine Voraussage hat sich bestätigt.", sec:"A" },
    { w:"voraussagen", a:"", pos:"v", en:"to predict", de:"vorher sagen, was passieren wird", s:"Niemand kann das Wetter für Monate voraussagen.", sec:"A" },
    { w:"Trend", a:"der", pl:"-s", pos:"n", en:"trend", de:"eine Entwicklung in eine bestimmte Richtung", s:"Der Trend geht zu wärmeren Wintern.", sec:"A" },
    { w:"Sonne", a:"die", pl:"-n", pos:"n", en:"sun", de:"der Stern, der uns Licht und Wärme gibt", s:"Heute scheint die Sonne den ganzen Tag.", sec:"A", c:"Die Sonne scheint." },
    { w:"Sonnenschein", a:"der", pl:"—", g:"nur Sg.", pos:"n", en:"sunshine", de:"das Licht der Sonne bei klarem Himmel", s:"Bei Sonnenschein sitzen alle draußen.", sec:"A" },
    { w:"sonnig", a:"", pos:"adj", en:"sunny", de:"mit viel Sonne", s:"Das Wochenende wird warm und sonnig.", sec:"A" },
    { w:"Niederschlag", a:"der", pl:"¨e", pos:"n", en:"precipitation", de:"Regen, Schnee oder Hagel, der vom Himmel fällt", s:"Im Norden fällt kräftiger Niederschlag.", sec:"A", c:"Niederschlag fällt" },
    { w:"Regen", a:"der", pl:"", pos:"n", en:"rain", de:"Wasser, das aus den Wolken fällt", s:"Nach dem Regen riecht die Luft frisch.", sec:"A" },
    { w:"Regenschauer", a:"der", pl:"-", pos:"n", en:"rain shower", de:"kurzer, kräftiger Regen", s:"Am Nachmittag gibt es einzelne Regenschauer.", sec:"A" },
    { w:"regnen", a:"", pos:"v", en:"to rain", de:"Wasser fällt aus den Wolken", s:"Es regnet seit heute Morgen ohne Pause.", sec:"A" },
    { w:"nieseln", a:"", pos:"v", en:"to drizzle", de:"ganz fein und leicht regnen", s:"Draußen nieselt es nur leicht.", sec:"A" },
    { w:"Gewitter", a:"das", pl:"-", pos:"n", en:"thunderstorm", de:"Sturm mit Blitz und Donner", s:"Am Abend zog ein heftiges Gewitter auf.", sec:"A" },
    { w:"gewittern", a:"", pos:"v", en:"to be thundery", de:"ein Gewitter geben", s:"Heute Abend wird es wahrscheinlich gewittern.", sec:"A" },
    { w:"Blitz", a:"der", pl:"-e", pos:"n", en:"lightning", de:"das helle Licht am Himmel beim Gewitter", s:"Ein Blitz erhellte den ganzen Himmel.", sec:"A" },
    { w:"blitzen", a:"", pos:"v", en:"to flash (lightning)", de:"ein Blitz erscheint am Himmel", s:"Es blitzt und donnert schon seit einer Stunde.", sec:"A" },
    { w:"Donner", a:"der", pl:"-", g:"meist Sg.", pos:"n", en:"thunder", de:"das laute Geräusch nach einem Blitz", s:"Der Donner war im ganzen Tal zu hören.", sec:"A" },
    { w:"donnern", a:"", pos:"v", en:"to thunder", de:"das laute Geräusch beim Gewitter machen", s:"Draußen donnert es sehr laut.", sec:"A" },
    { w:"Hagel", a:"der", pl:"-", g:"meist Sg.", pos:"n", en:"hail", de:"kleine Eiskugeln, die vom Himmel fallen", s:"Der Hagel hat die Ernte beschädigt.", sec:"A" },
    { w:"hageln", a:"", pos:"v", en:"to hail", de:"Eiskörner fallen vom Himmel", s:"Plötzlich fing es an zu hageln.", sec:"A" },
    { w:"Schnee", a:"der", pl:"—", g:"nur Sg.", pos:"n", en:"snow", de:"gefrorenes Wasser, das weiß vom Himmel fällt", s:"Im Januar lag überall Schnee.", sec:"A" },
    { w:"frieren", a:"", pos:"v", en:"to freeze, to be cold", de:"sehr kalt sein oder sich kalt fühlen", s:"Ohne Jacke friere ich sofort.", sec:"A" },
    { w:"Wolke", a:"die", pl:"-n", pos:"n", en:"cloud", de:"eine graue oder weiße Masse am Himmel", s:"Am Himmel ist keine einzige Wolke zu sehen.", sec:"A" },
    { w:"bewölkt", a:"", pos:"adj", en:"cloudy", de:"mit vielen Wolken am Himmel", s:"Morgen wird es stark bewölkt.", sec:"A" },
    { w:"bedeckt", a:"", pos:"adj", en:"overcast", de:"der Himmel ist ganz mit Wolken zu", s:"Der Himmel bleibt den ganzen Tag bedeckt.", sec:"A" },
    { w:"Nebel", a:"der", pl:"-", pos:"n", en:"fog", de:"feuchte Luft, durch die man schlecht sieht", s:"Am Morgen lag dichter Nebel über dem Fluss.", sec:"A" },
    { w:"neblig", a:"", pos:"adj", en:"foggy", de:"mit Nebel", s:"Fahr vorsichtig, es ist sehr neblig.", sec:"A" },
    { w:"Wind", a:"der", pl:"-e", pos:"n", en:"wind", de:"bewegte Luft", s:"Ein kalter Wind kommt von Norden.", sec:"A" },
    { w:"wehen", a:"", pos:"v", en:"to blow (of wind)", de:"sich als Luft bewegen", s:"Heute weht ein starker Wind.", sec:"A" },
    { w:"Sturm", a:"der", pl:"¨e", pos:"n", en:"storm", de:"sehr starker Wind", s:"Der Sturm hat mehrere Bäume umgeworfen.", sec:"A" },
    { w:"stürmen", a:"", pos:"v", en:"to be stormy", de:"sehr stark winden", s:"Draußen stürmt und regnet es.", sec:"A" },
    { w:"stürmisch", a:"", pos:"adj", en:"stormy", de:"mit starkem Wind", s:"Das Wetter an der Küste ist oft stürmisch.", sec:"A" },
    { w:"Orkan", a:"der", pl:"-e", pos:"n", en:"hurricane", de:"ein extrem starker Sturm", s:"Der Orkan richtete schwere Schäden an.", sec:"A" },
    { w:"Grad", a:"das", pl:"-e", pos:"n", en:"degree", de:"die Maßeinheit für die Temperatur", s:"Heute sind es nur acht Grad.", sec:"A", c:"Die Temperatur liegt bei 8 Grad." },
    { w:"Temperatur", a:"die", pl:"-en", pos:"n", en:"temperature", de:"wie warm oder kalt es ist", s:"Die Temperaturen steigen auf über 30 Grad.", sec:"A", c:"die Temperaturen steigen ≠ sinken / fallen" },
    { w:"erwärmen, sich", a:"", g:"≠ abkühlen, sich", pos:"v", en:"to warm up (≠ cool down)", de:"wärmer werden", s:"Die Luft erwärmt sich am Nachmittag deutlich.", sec:"A" },
    { w:"kühl / frisch", a:"", pos:"adj", en:"cool / chilly", de:"etwas kalt, aber nicht sehr kalt", s:"Am Abend wird es merklich kühler.", sec:"A", c:"kalt – kühl / frisch – mild – warm – heiß" },
    { w:"mild", a:"", pos:"adj", en:"mild", de:"angenehm warm, nicht extrem", s:"Wir hatten einen sehr milden Winter.", sec:"A" },
    { w:"schwül", a:"", pos:"adj", en:"muggy, humid", de:"warm und feucht, drückend", s:"Vor dem Gewitter ist die Luft oft schwül.", sec:"A" },
    { w:"feucht / nass", a:"", g:"≠ trocken", pos:"adj", en:"damp / wet (≠ dry)", de:"mit viel Wasser", s:"Nach dem Regen ist das Gras noch nass.", sec:"A" },
    { w:"Hochdruck", a:"der", pl:"—", g:"nur Sg.", pos:"n", en:"high pressure", de:"hoher Luftdruck, meist mit schönem Wetter", s:"Hochdruck bringt uns sonniges Wetter.", sec:"A" },
    { w:"Hochdruckgebiet", a:"das", pl:"-e", pos:"n", en:"high-pressure area", de:"ein Gebiet mit hohem Luftdruck", s:"Ein Hochdruckgebiet liegt über Mitteleuropa.", sec:"A" },
    { w:"Höchstwert", a:"der", pl:"-e", pos:"n", en:"maximum value / high", de:"der höchste gemessene Wert", s:"Die Höchstwerte liegen bei 35 Grad.", sec:"A" },
    { w:"Hitze", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"heat", de:"sehr hohe Temperaturen", s:"Bei dieser Hitze bleibe ich lieber drinnen.", sec:"A", c:"Es herrscht große Hitze." },
    { w:"Trockenheit", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"dryness, drought", de:"ein Zustand, in dem Wasser fehlt", s:"Die lange Trockenheit schadet den Feldern.", sec:"A" },
    { w:"Dürre", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"drought", de:"eine lange Zeit ohne Regen", s:"Die Dürre hat die Ernte zerstört.", sec:"A" },
    { w:"Klimawandel", a:"der", pl:"—", g:"nur Sg.", pos:"n", en:"climate change", de:"die langfristige Veränderung des Klimas", s:"Der Klimawandel betrifft die ganze Welt.", sec:"A" },
    { w:"Folge", a:"die", pl:"-n", pos:"n", en:"consequence", de:"das, was aus etwas entsteht", s:"Die Folgen der Hitze sind deutlich spürbar.", sec:"A" },
    { w:"Katastrophe", a:"die", pl:"-n", pos:"n", en:"catastrophe, disaster", de:"ein sehr schlimmes Unglück", s:"Die Überschwemmung war eine echte Katastrophe.", sec:"A" },
    { w:"gewöhnt sein an", a:"", g:"+ A", pos:"phr", en:"to be used to", de:"etwas kennen, weil es normal für einen ist", s:"Ich bin an heiße Sommer gewöhnt.", sec:"A" },
    { w:"empfinden", a:"", pos:"v", en:"to feel, to perceive", de:"etwas innerlich spüren", s:"Viele empfinden die Hitze als belastend.", sec:"A" },
    { w:"ertragen", a:"", pos:"v", en:"to bear, to endure", de:"etwas Schweres aushalten", s:"Diese Hitze kann ich kaum ertragen.", sec:"A" },
    { w:"leiden unter", a:"", g:"+ D", pos:"v", en:"to suffer from", de:"unter etwas Schwerem zu leiden haben", s:"Ältere Menschen leiden besonders unter der Hitze.", sec:"A" },
    { w:"ungewöhnlich", a:"", pos:"adj", en:"unusual", de:"nicht normal, selten", s:"Der Winter war ungewöhnlich mild.", sec:"A" },
    { w:"Kommentar", a:"der", pl:"-e", pos:"n", en:"comment, commentary", de:"ein Text, in dem jemand seine Meinung sagt", s:"Sie schrieb einen Kommentar zum Klimaschutz.", sec:"A" },
    { w:"objektiv", a:"", g:"≠ subjektiv", pos:"adj", en:"objective (≠ subjective)", de:"sachlich, ohne persönliche Meinung", s:"Ein Bericht sollte möglichst objektiv sein.", sec:"A" },
    { w:"sachlich", a:"", g:"≠ wertend", pos:"adj", en:"factual (≠ judgemental)", de:"nur bei den Fakten bleibend", s:"Bitte bleiben Sie sachlich in der Diskussion.", sec:"A" },
    // B — Meteorologie
    { w:"Meteorologie", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"meteorology", de:"die Wissenschaft vom Wetter", s:"Die Meteorologie erforscht Wetter und Klima.", sec:"B" },
    { w:"Prognose", a:"die", pl:"-n", pos:"n", en:"forecast, prognosis", de:"eine Vorhersage über die Zukunft", s:"Die Prognose für morgen ist unsicher.", sec:"B" },
    { w:"Wetterstation", a:"die", pl:"-en", pos:"n", en:"weather station", de:"ein Ort, an dem das Wetter gemessen wird", s:"Die Wetterstation misst Temperatur und Wind.", sec:"B" },
    { w:"Wettersatellit", a:"der", pl:"-en", pos:"n", en:"weather satellite", de:"ein Satellit, der das Wetter aus dem All beobachtet", s:"Wettersatelliten liefern Bilder der Wolken.", sec:"B" },
    { w:"Weltall", a:"das", pl:"—", g:"nur Sg.", pos:"n", en:"space, universe", de:"der Raum außerhalb der Erde", s:"Vom Weltall aus sieht man ganze Wettersysteme.", sec:"B" },
    { w:"Messung", a:"die", pl:"-en", pos:"n", en:"measurement", de:"das Bestimmen eines Wertes mit einem Gerät", s:"Die Messungen erfolgen jede Stunde.", sec:"B" },
    { w:"messen", a:"", pos:"v", en:"to measure", de:"mit einem Gerät einen Wert bestimmen", s:"Man misst die Temperatur im Schatten.", sec:"B" },
    { w:"Messinstrument", a:"das", pl:"-e", pos:"n", en:"measuring instrument", de:"ein Gerät zum Messen", s:"Die Messinstrumente müssen genau sein.", sec:"B" },
    { w:"Messgerät", a:"das", pl:"-e", pos:"n", en:"measuring device", de:"ein Apparat, mit dem man misst", s:"Das Messgerät zeigt die Luftfeuchtigkeit an.", sec:"B" },
    { w:"aufstellen", a:"", pos:"v", en:"to set up, to install", de:"etwas an einen Platz stellen", s:"Man hat neue Messgeräte aufgestellt.", sec:"B" },
    { w:"Thermometer", a:"das", pl:"-", pos:"n", en:"thermometer", de:"ein Gerät, das die Temperatur misst", s:"Das Thermometer zeigt 28 Grad.", sec:"B" },
    { w:"Barometer", a:"das", pl:"-", pos:"n", en:"barometer", de:"ein Gerät, das den Luftdruck misst", s:"Das Barometer fällt, es gibt bald Regen.", sec:"B" },
    { w:"Luft", a:"die", pl:"¨e", pos:"n", en:"air", de:"das Gasgemisch, das wir atmen", s:"Nach dem Gewitter ist die Luft klar.", sec:"B" },
    { w:"Luftdruck", a:"der", pl:"—", g:"nur Sg.", pos:"n", en:"air pressure", de:"der Druck der Luft auf die Erde", s:"Ein fallender Luftdruck kündigt schlechtes Wetter an.", sec:"B" },
    { w:"Hygrometer", a:"das", pl:"-", pos:"n", en:"hygrometer", de:"ein Gerät, das die Luftfeuchtigkeit misst", s:"Das Hygrometer zeigt 70 Prozent an.", sec:"B" },
    { w:"Feuchtigkeit", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"humidity, moisture", de:"die Menge an Wasser in der Luft", s:"Die hohe Feuchtigkeit macht die Hitze schlimmer.", sec:"B", c:"Luftfeuchtigkeit" },
    { w:"Windmesser", a:"der", pl:"-", pos:"n", en:"anemometer", de:"ein Gerät, das die Windgeschwindigkeit misst", s:"Der Windmesser zeigt starke Böen an.", sec:"B" },
    { w:"Windgeschwindigkeit", a:"die", pl:"-en", pos:"n", en:"wind speed", de:"wie schnell sich die Luft bewegt", s:"Die Windgeschwindigkeit erreicht 90 km/h.", sec:"B" },
    { w:"Wetterfahne", a:"die", pl:"-n", pos:"n", en:"weather vane", de:"ein Gerät, das die Windrichtung zeigt", s:"Die Wetterfahne dreht sich nach Westen.", sec:"B" },
    { w:"Windrichtung", a:"die", pl:"-en", pos:"n", en:"wind direction", de:"die Richtung, aus der der Wind kommt", s:"Die Windrichtung ändert sich am Abend.", sec:"B" },
    { w:"Niederschlagsmesser", a:"der", pl:"-", pos:"n", en:"rain gauge", de:"ein Gerät, das die Regenmenge misst", s:"Der Niederschlagsmesser stand voll Wasser.", sec:"B" },
    { w:"Regenmenge", a:"die", pl:"-n", pos:"n", en:"amount of rainfall", de:"wie viel Regen gefallen ist", s:"Die Regenmenge war dieses Jahr zu gering.", sec:"B" },
    { w:"Erscheinung", a:"die", pl:"-en", pos:"n", en:"phenomenon, appearance", de:"etwas, das man beobachten kann", s:"Extremwetter ist keine seltene Erscheinung mehr.", sec:"B" },
    { w:"Philosoph", a:"der", pl:"-en", pos:"n", en:"philosopher", de:"ein Denker, der über große Fragen nachdenkt", s:"Schon antike Philosophen beobachteten das Wetter.", sec:"B" },
    { w:"Forscher", a:"der", pl:"-", pos:"n", en:"researcher", de:"eine Person, die wissenschaftlich untersucht", s:"Die Forscher werten die Daten aus.", sec:"B" },
    { w:"Ehrenamtliche", a:"der / die", pl:"-n", pos:"n", en:"volunteer", de:"eine Person, die ohne Bezahlung hilft", s:"Viele Ehrenamtliche melden täglich Wetterdaten.", sec:"B" },
    { w:"Fortschritt", a:"der", pl:"-e", pos:"n", en:"progress", de:"eine Entwicklung nach vorn, Verbesserung", s:"Der technische Fortschritt verbessert die Prognosen.", sec:"B" },
    { w:"Erfindung", a:"die", pl:"-en", pos:"n", en:"invention", de:"etwas Neues, das jemand entwickelt hat", s:"Die Erfindung des Thermometers war entscheidend.", sec:"B" },
    { w:"Telegrafie", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"telegraphy", de:"die Übertragung von Nachrichten über Leitungen", s:"Dank der Telegrafie konnte man Wetterdaten schnell senden.", sec:"B" },
    { w:"Branche", a:"die", pl:"-n", pos:"n", en:"industry, sector", de:"ein bestimmter Wirtschaftsbereich", s:"Viele Branchen sind vom Wetter abhängig.", sec:"B" },
    { w:"Flugverkehr", a:"der", pl:"—", g:"nur Sg.", pos:"n", en:"air traffic", de:"alle Flüge und der Betrieb der Flugzeuge", s:"Der Flugverkehr leidet unter starkem Nebel.", sec:"B" },
    { w:"Baugewerbe", a:"das", pl:"—", g:"nur Sg.", pos:"n", en:"construction industry", de:"die Branche, die Gebäude baut", s:"Das Baugewerbe braucht trockenes Wetter.", sec:"B" },
    { w:"abhängig sein von", a:"", g:"+ D", pos:"phr", en:"to depend on", de:"auf etwas angewiesen sein", s:"Die Landwirtschaft ist stark vom Wetter abhängig.", sec:"B" },
    { w:"wetterabhängig", a:"", pos:"adj", en:"weather-dependent", de:"vom Wetter beeinflusst", s:"Viele Berufe sind wetterabhängig.", sec:"B" },
    { w:"präzise", a:"", pos:"adj", en:"precise", de:"genau und exakt", s:"Moderne Prognosen sind sehr präzise.", sec:"B" },
    { w:"stammen aus", a:"", g:"+ D", pos:"v", en:"to originate from", de:"seinen Ursprung an einem Ort haben", s:"Die Daten stammen aus mehreren Wetterstationen.", sec:"B" },
    // C — Klimawandel
    { w:"Wetteraufzeichnung", a:"die", pl:"-en", pos:"n", en:"weather record", de:"die gespeicherten Daten über das Wetter", s:"Seit 1881 gibt es genaue Wetteraufzeichnungen.", sec:"C" },
    { w:"Wärme", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"warmth, heat", de:"der Zustand, warm zu sein", s:"Die Wärme bleibt bis in die Nacht.", sec:"C" },
    { w:"Erderwärmung", a:"die", pl:"-en", pos:"n", en:"global warming", de:"das Wärmerwerden der ganzen Erde", s:"Die Erderwärmung schreitet schneller voran als gedacht.", sec:"C" },
    { w:"Klimaveränderung", a:"die", pl:"-en", pos:"n", en:"climate change", de:"die Veränderung des Klimas über lange Zeit", s:"Die Klimaveränderung zeigt sich in Extremwetter.", sec:"C" },
    { w:"Extremwetter", a:"das", pl:"—", g:"nur Sg.", pos:"n", en:"extreme weather", de:"sehr starkes, gefährliches Wetter", s:"Extremwetter tritt immer häufiger auf.", sec:"C" },
    { w:"Ursache", a:"die", pl:"-n", pos:"n", en:"cause", de:"der Grund, warum etwas passiert", s:"Die Ursache des Problems ist der hohe CO2-Ausstoß.", sec:"C" },
    { w:"verursachen", a:"", pos:"v", en:"to cause", de:"der Grund für etwas sein", s:"Der Mensch verursacht den größten Teil der Erwärmung.", sec:"C" },
    { w:"Auswirkung", a:"die", pl:"-en", pos:"n", en:"effect, impact", de:"die Folge, die etwas hat", s:"Die Auswirkungen sind weltweit zu spüren.", sec:"C" },
    { w:"Energie", a:"die", pl:"-n", pos:"n", en:"energy", de:"die Kraft, mit der Maschinen und Geräte laufen", s:"Wir brauchen mehr erneuerbare Energie.", sec:"C", c:"erneuerbare Energie" },
    { w:"Energiewende", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"energy transition", de:"der Wechsel zu erneuerbaren Energien", s:"Die Energiewende ist eine große Aufgabe.", sec:"C" },
    { w:"Energieträger", a:"der", pl:"-", pos:"n", en:"energy source", de:"ein Stoff, aus dem man Energie gewinnt", s:"Kohle ist ein besonders schädlicher Energieträger.", sec:"C" },
    { w:"Energiegewinnung", a:"die", pl:"-en", pos:"n", en:"energy generation", de:"das Herstellen von Energie", s:"Die Energiegewinnung aus Wind wächst stark.", sec:"C" },
    { w:"Stromerzeugung", a:"die", pl:"-en", pos:"n", en:"electricity generation", de:"das Produzieren von Strom", s:"Die Stromerzeugung soll klimaneutral werden.", sec:"C" },
    { w:"Kraftwerk", a:"das", pl:"-e", pos:"n", en:"power plant", de:"eine Anlage, die Strom produziert", s:"Das alte Kraftwerk wird abgeschaltet.", sec:"C" },
    { w:"Brennstoff", a:"der", pl:"-", pos:"n", en:"fuel", de:"ein Stoff, den man verbrennt, um Energie zu bekommen", s:"Fossile Brennstoffe belasten das Klima.", sec:"C", c:"fossile Brennstoffe" },
    { w:"Öl", a:"das", pl:"—", g:"hier nur Sg.", pos:"n", en:"oil", de:"ein flüssiger fossiler Brennstoff", s:"Öl ist noch immer ein wichtiger Energieträger.", sec:"C" },
    { w:"Gas", a:"das", pl:"—", g:"hier nur Sg.", pos:"n", en:"gas", de:"ein gasförmiger Brennstoff", s:"Viele Haushalte heizen mit Gas.", sec:"C" },
    { w:"Kohle", a:"die", pl:"—", g:"hier nur Sg.", pos:"n", en:"coal", de:"ein schwarzer fossiler Brennstoff", s:"Die Verbrennung von Kohle setzt viel CO2 frei.", sec:"C" },
    { w:"Verbrennung", a:"die", pl:"-en", pos:"n", en:"combustion, burning", de:"das Verbrennen von etwas", s:"Bei der Verbrennung entsteht Kohlendioxid.", sec:"C" },
    { w:"Kohlendioxid", a:"das", pl:"—", g:"hier nur Sg.", pos:"n", en:"carbon dioxide", de:"das Gas CO2, das die Erde erwärmt", s:"Kohlendioxid ist das wichtigste Treibhausgas.", sec:"C" },
    { w:"Massentierhaltung", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"factory farming", de:"das Halten sehr vieler Tiere auf engem Raum", s:"Die Massentierhaltung schadet dem Klima.", sec:"C" },
    { w:"Verdauung", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"digestion", de:"das Verarbeiten der Nahrung im Körper", s:"Bei der Verdauung der Kühe entsteht Methan.", sec:"C" },
    { w:"Klimakiller", a:"der", pl:"-", pos:"n", en:"climate killer", de:"etwas, das dem Klima besonders schadet", s:"Der Verkehr gilt als großer Klimakiller.", sec:"C" },
    { w:"klimaschädlich", a:"", pos:"adj", en:"harmful to the climate", de:"schlecht für das Klima", s:"Fliegen ist besonders klimaschädlich.", sec:"C" },
    { w:"Treibhauseffekt", a:"der", pl:"-e", pos:"n", en:"greenhouse effect", de:"das Aufheizen der Erde durch Gase in der Atmosphäre", s:"Der Treibhauseffekt verstärkt sich durch CO2.", sec:"C" },
    { w:"natürlich", a:"", g:"≠ anthropogen", pos:"adj", en:"natural (≠ man-made)", de:"von der Natur, nicht vom Menschen gemacht", s:"Es gibt einen natürlichen Treibhauseffekt.", sec:"C" },
    { w:"Sonnenstrahl", a:"der", pl:"-en", pos:"n", en:"sun ray", de:"das Licht, das von der Sonne kommt", s:"Die Sonnenstrahlen erwärmen die Erdoberfläche.", sec:"C" },
    { w:"Atmosphäre", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"atmosphere", de:"die Lufthülle um die Erde", s:"In der Atmosphäre sammelt sich immer mehr CO2.", sec:"C" },
    { w:"Gasschicht", a:"die", pl:"-en", pos:"n", en:"layer of gas", de:"eine Lage aus Gas", s:"Die Gasschicht hält die Wärme zurück.", sec:"C" },
    { w:"schwitzen", a:"", pos:"v", en:"to sweat", de:"bei Hitze Wasser über die Haut verlieren", s:"Bei 35 Grad schwitzt man ständig.", sec:"C" },
    { w:"wirken", a:"", pos:"v", en:"to act, to work (like)", de:"eine bestimmte Wirkung haben", s:"Die Gasschicht wirkt wie eine Glasscheibe.", sec:"C", c:"wirken wie eine Glasscheibe" },
    { w:"verhindern", a:"", pos:"v", en:"to prevent", de:"dafür sorgen, dass etwas nicht passiert", s:"Wir müssen eine weitere Erwärmung verhindern.", sec:"C" },
    { w:"verstärken", a:"", pos:"v", en:"to intensify, to amplify", de:"stärker machen", s:"Der Mensch verstärkt den Treibhauseffekt.", sec:"C" },
    { w:"erhöhen", a:"", pos:"v", en:"to raise, to increase", de:"höher oder größer machen", s:"CO2 erhöht die Temperatur der Erde.", sec:"C" },
    { w:"abgeben", a:"", g:"≠ zurückhalten", pos:"v", en:"to give off (≠ retain)", de:"etwas nach außen weitergeben", s:"Die Erde gibt Wärme an die Atmosphäre ab.", sec:"C" },
    { w:"Arktis", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"the Arctic", de:"die Region um den Nordpol", s:"In der Arktis schmilzt das Eis besonders schnell.", sec:"C" },
    { w:"Meeresspiegel", a:"der", pl:"-", pos:"n", en:"sea level", de:"die Höhe der Meeresoberfläche", s:"Der Meeresspiegel steigt weltweit an.", sec:"C" },
    { w:"ansteigen", a:"", pos:"v", en:"to rise", de:"höher werden", s:"Die Temperaturen steigen seit Jahren an.", sec:"C" },
    { w:"Anstieg", a:"der", pl:"-e", pos:"n", en:"rise, increase", de:"das Höherwerden von etwas", s:"Der Anstieg der Meere bedroht viele Städte.", sec:"C" },
    { w:"schmelzen", a:"", pos:"v", en:"to melt", de:"von fest zu flüssig werden", s:"Die Gletscher schmelzen immer schneller.", sec:"C" },
    { w:"versinken", a:"", pos:"v", en:"to sink, to be submerged", de:"im Wasser untergehen", s:"Ganze Inseln könnten im Meer versinken.", sec:"C" },
    { w:"Hitzewelle", a:"die", pl:"-n", pos:"n", en:"heat wave", de:"eine lange Zeit mit sehr hohen Temperaturen", s:"Die Hitzewelle dauerte drei Wochen.", sec:"C" },
    { w:"Starkregen", a:"der", pl:"-", pos:"n", en:"heavy rain", de:"sehr kräftiger Regen in kurzer Zeit", s:"Starkregen führte zu Überschwemmungen.", sec:"C" },
    { w:"überfluten", a:"", pos:"v", en:"to flood", de:"mit Wasser bedecken", s:"Der Fluss hat die Felder überflutet.", sec:"C" },
    { w:"über die Ufer treten", a:"", pos:"phr", en:"to burst its banks", de:"aus dem Flussbett heraustreten", s:"Nach dem Regen trat der Fluss über die Ufer.", sec:"C" },
    { w:"heftig", a:"", pos:"adj", en:"heavy, violent", de:"sehr stark und kräftig", s:"Heftige Stürme werden häufiger.", sec:"C" },
    { w:"umsteigen", a:"", pos:"v", en:"to switch (to sth)", de:"von einer Sache zu einer anderen wechseln", s:"Viele steigen auf erneuerbare Energien um.", sec:"C" },
    { w:"aussterben", a:"", pos:"v", en:"to become extinct", de:"als Art ganz verschwinden", s:"Viele Tierarten sterben durch den Klimawandel aus.", sec:"C", c:"vom Aussterben bedroht sein" },
    { w:"Sterblichkeitsrate", a:"die", pl:"-n", pos:"n", en:"mortality rate", de:"wie viele Menschen in einer Zeit sterben", s:"Bei Hitzewellen steigt die Sterblichkeitsrate.", sec:"C" },
    { w:"Waldbrand", a:"der", pl:"¨e", pos:"n", en:"forest fire", de:"ein großes Feuer im Wald", s:"Trockenheit begünstigt Waldbrände.", sec:"C" },
    { w:"austrocknen", a:"", pos:"v", en:"to dry out", de:"ganz trocken werden", s:"Bei Dürre trocknen die Böden völlig aus.", sec:"C" },
    // D — Folgen des Klimawandels
    { w:"Kurve", a:"die", pl:"-n", pos:"n", en:"curve, graph line", de:"die Linie in einer Grafik", s:"Die Kurve zeigt einen klaren Anstieg.", sec:"D" },
    { w:"zunehmen", a:"", pos:"v", en:"to increase", de:"mehr oder größer werden", s:"Die Zahl der Hitzetage nimmt deutlich zu.", sec:"D" },
    { w:"spürbar", a:"", pos:"adj", en:"noticeable, palpable", de:"so, dass man es deutlich merkt", s:"Der Klimawandel ist bereits spürbar.", sec:"D" },
    { w:"Überflutung", a:"die", pl:"-en", pos:"n", en:"flooding", de:"das Bedecken von Land mit Wasser", s:"Die Überflutungen zerstörten viele Häuser.", sec:"D" },
    { w:"Regenzeit", a:"die", pl:"-en", pos:"n", en:"rainy season", de:"die Jahreszeit mit viel Regen", s:"In manchen Ländern fällt die Regenzeit aus.", sec:"D" },
    { w:"ausfallen", a:"", pos:"v", en:"to be cancelled, to fail to occur", de:"nicht stattfinden", s:"Wenn die Regenzeit ausfällt, verdorrt die Ernte.", sec:"D" },
    { w:"Wasserverbrauch", a:"der", pl:"—", g:"nur Sg.", pos:"n", en:"water consumption", de:"die Menge Wasser, die man nutzt", s:"Wir müssen unseren Wasserverbrauch senken.", sec:"D" },
    { w:"senken", a:"", pos:"v", en:"to lower, to reduce", de:"kleiner oder niedriger machen", s:"Die Stadt will den CO2-Ausstoß senken.", sec:"D" },
    { w:"um seine Existenz kämpfen", a:"", pos:"phr", en:"to fight for one's livelihood", de:"darum kämpfen, weiterleben oder weiterarbeiten zu können", s:"Viele Bauern kämpfen um ihre Existenz.", sec:"D" },
    { w:"Verluste erzeugen", a:"", pos:"phr", en:"to generate losses", de:"dazu führen, dass man Geld oder Dinge verliert", s:"Die Dürre erzeugt hohe Verluste in der Landwirtschaft.", sec:"D" },
    { w:"auf der einen Seite – auf der anderen Seite", a:"", pos:"phr", en:"on the one hand – on the other hand", de:"drückt zwei gegensätzliche Sichtweisen aus", s:"Auf der einen Seite hilft Technik, auf der anderen Seite kostet sie viel.", sec:"D" },
    { w:"Maßnahme", a:"die", pl:"-n", pos:"n", en:"measure, action", de:"eine Handlung, um ein Problem zu lösen", s:"Die Regierung beschließt neue Maßnahmen zum Klimaschutz.", sec:"D" }
  ]
};
