/* Lektion 4 — Wortschatz */
window.DECK = window.DECK || { lessons: {} };
window.DECK.lessons[4] = {
  title: "Digitale Welten",
  subtitle: "Digitalisierung, Jobmesse & Smart Home",
  cards: [
    // A — Digitale Welten
    { w:"digital", a:"", pos:"adj", en:"digital", de:"mit Computern und elektronischen Daten", s:"Immer mehr Dienste laufen rein digital.", sec:"A" },
    { w:"Digitalisierung", a:"die", pl:"-en", pos:"n", en:"digitalization", de:"die Umstellung auf digitale Technik", s:"Die Digitalisierung verändert auch die Medizin.", sec:"A" },
    { w:"Aspekt", a:"der", pl:"-e", pos:"n", en:"aspect", de:"eine bestimmte Seite oder ein Gesichtspunkt einer Sache", s:"Wir betrachten Vor- und Nachteile unter jedem Aspekt.", sec:"A" },
    { w:"Beratung", a:"die", pl:"-en", pos:"n", en:"consultation, advice", de:"ein Gespräch, in dem man Rat bekommt", s:"Vor der Operation holt sie sich eine Beratung.", sec:"A", c:"sich Beratung holen" },
    { w:"Kreativität", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"creativity", de:"die Fähigkeit, Neues und Fantasievolles zu schaffen", s:"Digitale Werkzeuge fördern die Kreativität.", sec:"A" },
    { w:"Komfort", a:"der", pl:"—", g:"nur Sg.", pos:"n", en:"comfort, convenience", de:"eine angenehme Bequemlichkeit", s:"Online-Termine bieten viel Komfort.", sec:"A" },
    { w:"Isolation", a:"die", pl:"—", g:"hier nur Sg.", pos:"n", en:"isolation", de:"das Getrenntsein von anderen Menschen", s:"Zu viel Bildschirmzeit kann zu Isolation führen.", sec:"A" },
    { w:"Verfügbarkeit", a:"die", pl:"-en", pos:"n", en:"availability", de:"die Tatsache, dass etwas zur Verfügung steht", s:"Die ständige Verfügbarkeit von Ärzten online ist praktisch.", sec:"A" },
    { w:"Serie", a:"die", pl:"-n", pos:"n", en:"series", de:"eine Folge von Sendungen oder Dingen", s:"Abends streamt er gern eine Serie.", sec:"A" },
    { w:"online", a:"", pos:"adj", en:"online", de:"mit dem Internet verbunden", s:"Ich bin fast den ganzen Tag online.", sec:"A" },
    { w:"Online-Banking", a:"das", pl:"—", g:"nur Sg.", pos:"n", en:"online banking", de:"das Erledigen von Bankgeschäften im Internet", s:"Beim Online-Banking sollte man auf Sicherheit achten.", sec:"A" },
    { w:"bloggen", a:"", pos:"v", en:"to blog", de:"regelmäßig Texte im Internet veröffentlichen", s:"Sie bloggt über ihr Leben in Berlin.", sec:"A" },
    { w:"chatten", a:"", pos:"v", en:"to chat (online)", de:"sich online per Textnachrichten unterhalten", s:"Wir chatten jeden Abend kurz.", sec:"A" },
    { w:"posten", a:"", pos:"v", en:"to post", de:"etwas online veröffentlichen", s:"Er postet täglich Fotos in sozialen Netzwerken.", sec:"A" },
    { w:"simsen", a:"", pos:"v", en:"to text (SMS)", de:"eine SMS schreiben", s:"Früher haben wir viel gesimst.", sec:"A" },
    { w:"skypen", a:"", pos:"v", en:"to Skype", de:"über Skype telefonieren oder Video anrufen", s:"Mit meiner Familie skype ich jeden Sonntag.", sec:"A" },
    { w:"streamen", a:"", pos:"v", en:"to stream", de:"Filme oder Musik direkt aus dem Internet ansehen/hören", s:"Wir streamen den Film heute Abend.", sec:"A" },
    { w:"twittern", a:"", pos:"v", en:"to tweet", de:"kurze Nachrichten auf Twitter/X schreiben", s:"Der Politiker twittert mehrmals am Tag.", sec:"A" },
    { w:"whatsappen", a:"", pos:"v", en:"to WhatsApp", de:"Nachrichten über WhatsApp schreiben", s:"Kannst du mir die Adresse whatsappen?", sec:"A" },
    { w:"App", a:"die", pl:"-s", pos:"n", en:"app", de:"ein kleines Programm für Handy oder Tablet", s:"Für Arzttermine gibt es jetzt eine praktische App.", sec:"A" },
    { w:"Telemedizin", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"telemedicine", de:"medizinische Behandlung über das Internet aus der Ferne", s:"Auf dem Land hilft die Telemedizin bei langen Wegen.", sec:"A", c:"Telemedizin einsetzen" },
    { w:"E-Health", a:"", g:"ohne Artikel, nur Sg.", pos:"n", en:"e-health", de:"die Nutzung digitaler Technik im Gesundheitswesen", s:"E-Health umfasst Apps, Online-Termine und digitale Akten.", sec:"A" },
    { w:"Technologie", a:"die", pl:"-n", pos:"n", en:"technology", de:"die Anwendung von technischem Wissen", s:"Neue Technologien erleichtern die Diagnose.", sec:"A" },
    { w:"Telekommunikation", a:"die", pl:"-en", pos:"n", en:"telecommunication", de:"die Übertragung von Informationen über große Entfernungen", s:"Die Telekommunikation macht Ferngespräche möglich.", sec:"A" },
    { w:"Vernetzung", a:"die", pl:"-en", pos:"n", en:"networking, interconnection", de:"das Verbinden von Geräten oder Menschen", s:"Die Vernetzung der Kliniken verbessert die Versorgung.", sec:"A" },
    { w:"Austausch", a:"der", pl:"-", pos:"n", en:"exchange", de:"das gegenseitige Geben und Nehmen von etwas", s:"Der Austausch von Daten muss sicher sein.", sec:"A", c:"Datenaustausch" },
    { w:"Datenübermittlung", a:"die", pl:"-en", pos:"n", en:"data transmission", de:"das Senden von Daten von einem Ort zum anderen", s:"Die Datenübermittlung erfolgt verschlüsselt.", sec:"A" },
    { w:"Videochat", a:"der", pl:"-s", pos:"n", en:"video chat", de:"ein Gespräch mit Bild über das Internet", s:"Der Arzt berät die Patientin im Videochat.", sec:"A" },
    { w:"mobil", a:"", pos:"adj", en:"mobile", de:"beweglich, überall nutzbar", s:"Mit dem Handy bin ich mobil erreichbar.", sec:"A" },
    { w:"Nutzen", a:"der", pl:"-", pos:"n", en:"benefit, use", de:"der Vorteil, den etwas bringt", s:"Der Nutzen der App liegt auf der Hand.", sec:"A" },
    { w:"Einsatz", a:"der", pl:"¨e", pos:"n", en:"use, deployment", de:"das Verwenden von etwas für einen Zweck", s:"Der Einsatz von Robotern in Kliniken nimmt zu.", sec:"A" },
    { w:"Anwendung", a:"die", pl:"-en", pos:"n", en:"application, use", de:"das praktische Benutzen von etwas", s:"Die Anwendung der Software ist einfach.", sec:"A" },
    { w:"Bereich", a:"der", pl:"-e", pos:"n", en:"area, field", de:"ein bestimmter Teil oder ein Themengebiet", s:"Im Bereich der Medizin gibt es viele neue Apps.", sec:"A" },
    { w:"Erkrankung", a:"die", pl:"-en", pos:"n", en:"illness, disease", de:"eine Krankheit", s:"Chronische Erkrankungen lassen sich digital gut begleiten.", sec:"A" },
    { w:"Beschwerde", a:"die", pl:"-n", pos:"n", en:"complaint, ailment", de:"ein körperliches Problem oder Schmerz", s:"Bei leichten Beschwerden hilft oft eine Online-Beratung.", sec:"A" },
    { w:"Symptom", a:"das", pl:"-e", pos:"n", en:"symptom", de:"ein Zeichen für eine Krankheit", s:"Fieber ist ein häufiges Symptom.", sec:"A" },
    { w:"Diagnose", a:"die", pl:"-n", pos:"n", en:"diagnosis", de:"die Feststellung, welche Krankheit jemand hat", s:"Die Ärztin stellte schnell eine Diagnose.", sec:"A" },
    { w:"Diagnostik", a:"die", pl:"-en", pos:"n", en:"diagnostics", de:"die Methoden, um Krankheiten festzustellen", s:"Die digitale Diagnostik wird immer genauer.", sec:"A" },
    { w:"Einschätzung", a:"die", pl:"-en", pos:"n", en:"assessment, estimate", de:"eine Meinung darüber, wie etwas ist", s:"Ich möchte eine zweite Einschätzung zu meinen Werten.", sec:"A" },
    { w:"einschätzen", a:"", pos:"v", en:"to assess, to estimate", de:"beurteilen, wie etwas ist", s:"Der Arzt kann das Risiko gut einschätzen.", sec:"A" },
    { w:"Therapie", a:"die", pl:"-n", pos:"n", en:"therapy, treatment", de:"die Behandlung einer Krankheit", s:"Die Therapie dauert mehrere Wochen.", sec:"A" },
    { w:"Behandlung", a:"die", pl:"-en", pos:"n", en:"treatment", de:"das medizinische Versorgen eines Patienten", s:"Die Behandlung kann teils online erfolgen.", sec:"A" },
    { w:"räumlich getrennt", a:"", pos:"phr", en:"spatially separated", de:"an verschiedenen Orten, nicht am gleichen Platz", s:"Arzt und Patient sind räumlich getrennt.", sec:"A" },
    { w:"zeitlich versetzt", a:"", pos:"phr", en:"at different times", de:"nicht gleichzeitig, zu verschiedenen Zeiten", s:"Die Nachrichten werden oft zeitlich versetzt beantwortet.", sec:"A" },
    { w:"Distanz", a:"die", pl:"-en", pos:"n", en:"distance", de:"der räumliche Abstand zwischen zwei Punkten", s:"Die Telemedizin überwindet große Distanzen.", sec:"A" },
    { w:"Zweitmeinung", a:"die", pl:"-en", pos:"n", en:"second opinion", de:"die Meinung eines zweiten Arztes", s:"Bei einer schweren Diagnose hole ich eine Zweitmeinung ein.", sec:"A", c:"eine Zweitmeinung einholen" },
    { w:"Spezialist", a:"der", pl:"-en", pos:"n", en:"specialist", de:"ein Experte für ein bestimmtes Gebiet", s:"Für seltene Fälle zieht man einen Spezialisten hinzu.", sec:"A", c:"einen Spezialisten hinzuziehen" },
    { w:"ärztlich", a:"", pos:"adj", en:"medical (of a doctor)", de:"vom Arzt, den Arzt betreffend", s:"Bei starken Schmerzen braucht man ärztlichen Rat.", sec:"A" },
    { w:"niedergelassen", a:"", pos:"adj", en:"(doctor) in private practice", de:"mit eigener Praxis arbeitend", s:"Der niedergelassene Arzt hat seine eigene Praxis.", sec:"A", c:"der niedergelassene Arzt" },
    { w:"aufsuchen", a:"", pos:"v", en:"to go to see, to consult", de:"zu jemandem oder an einen Ort gehen (z. B. Arzt)", s:"Bei starken Beschwerden sollte man einen Arzt aufsuchen.", sec:"A", c:"einen Arzt aufsuchen" },
    { w:"konsultieren", a:"", pos:"v", en:"to consult", de:"jemanden um fachlichen Rat fragen", s:"Sie konsultierte online einen Facharzt.", sec:"A", c:"einen Arzt konsultieren" },
    { w:"ersetzen", a:"", pos:"v", en:"to replace", de:"etwas an die Stelle von etwas anderem setzen", s:"Online-Termine können den Arztbesuch nicht ganz ersetzen.", sec:"A" },
    { w:"reduzieren", a:"", pos:"v", en:"to reduce", de:"weniger oder kleiner machen", s:"Die App reduziert unnötige Wege.", sec:"A" },
    { w:"ländlich", a:"", pos:"adj", en:"rural", de:"auf dem Land, nicht in der Stadt", s:"In ländlichen Regionen fehlen oft Ärzte.", sec:"A" },
    { w:"Notfall", a:"der", pl:"¨e", pos:"n", en:"emergency", de:"eine plötzliche, gefährliche Situation", s:"Im Notfall wähle ich die 112.", sec:"A" },
    { w:"Rettungswagen", a:"der", pl:"- / ¨", pos:"n", en:"ambulance", de:"ein Fahrzeug, das Kranke schnell ins Krankenhaus bringt", s:"Der Rettungswagen war in wenigen Minuten da.", sec:"A" },
    { w:"Ambulanz", a:"die", pl:"-en", pos:"n", en:"outpatient clinic, A&E", de:"die Notaufnahme oder ärztliche Anlaufstelle im Krankenhaus", s:"In der Ambulanz musste ich lange warten.", sec:"A" },
    { w:"Wartebereich", a:"der", pl:"-e", pos:"n", en:"waiting area", de:"der Ort, an dem man auf etwas wartet", s:"Der Wartebereich war voll besetzt.", sec:"A" },
    { w:"Wartezeit", a:"die", pl:"-en", pos:"n", en:"waiting time", de:"die Zeit, die man warten muss", s:"Digitale Termine verkürzen die Wartezeit.", sec:"A" },
    { w:"überlaufen sein", a:"", pos:"phr", en:"to be overcrowded", de:"zu voll sein, weil zu viele Menschen kommen", s:"Die Notaufnahmen sind oft überlaufen.", sec:"A" },
    { w:"gesetzlich", a:"", pos:"adj", en:"legal, statutory", de:"durch das Gesetz bestimmt", s:"Der Datenschutz ist gesetzlich geregelt.", sec:"A" },
    { w:"aufheben", a:"", pos:"v", en:"to abolish; to keep", de:"etwas beenden oder ungültig machen", s:"Die Regel wurde inzwischen aufgehoben.", sec:"A" },
    { w:"Privatsphäre", a:"die", pl:"-n", pos:"n", en:"privacy", de:"der persönliche Bereich, den andere nichts angeht", s:"Digitale Akten dürfen die Privatsphäre nicht verletzen.", sec:"A" },
    { w:"Infrastruktur", a:"die", pl:"-en", pos:"n", en:"infrastructure", de:"die grundlegenden Einrichtungen wie Netze, Straßen, Leitungen", s:"Für Telemedizin braucht man eine gute digitale Infrastruktur.", sec:"A" },
    { w:"vertrauen auf", a:"", g:"+ A", pos:"v", en:"to rely / trust on", de:"sich auf etwas verlassen", s:"Man muss auf den Datenschutz vertrauen können.", sec:"A" },
    { w:"Akte", a:"die", pl:"-n", pos:"n", en:"file, record", de:"eine Sammlung von Dokumenten über eine Person", s:"Die digitale Akte enthält alle Befunde.", sec:"A" },
    { w:"Finanzen", a:"die", pl:"", g:"nur Pl.", pos:"n", en:"finances", de:"das Geld und die Geldangelegenheiten einer Person", s:"Online-Banking macht die Finanzen leicht steuerbar.", sec:"A" },
    { w:"Diebstahl", a:"der", pl:"¨e", pos:"n", en:"theft", de:"das Stehlen von etwas", s:"Datendiebstahl ist eine ernste Gefahr.", sec:"A" },
    { w:"Manipulation", a:"die", pl:"-en", pos:"n", en:"manipulation, tampering", de:"das heimliche, unerlaubte Verändern von etwas", s:"Manipulation von Daten muss verhindert werden.", sec:"A" },
    { w:"Missbrauch", a:"der", pl:"—", g:"Pl. selten", pos:"n", en:"misuse, abuse", de:"das falsche oder schädliche Verwenden von etwas", s:"Der Missbrauch persönlicher Daten ist strafbar.", sec:"A" },
    { w:"Befragte", a:"der / die", pl:"-n", pos:"n", en:"respondent, person surveyed", de:"eine Person, die man in einer Umfrage befragt", s:"Die meisten Befragten finden Telemedizin sinnvoll.", sec:"A" },
    { w:"kritisieren", a:"", pos:"v", en:"to criticize", de:"sagen, was an etwas schlecht ist", s:"Viele kritisieren den mangelnden Datenschutz.", sec:"A" },
    { w:"verloren gehen", a:"", pos:"phr", en:"to get lost", de:"nicht mehr da sein, abhandenkommen", s:"Bei schlechter Technik können Daten verloren gehen.", sec:"A" },
    { w:"auf der Hand liegen", a:"", pos:"phr", en:"to be obvious", de:"ganz klar und leicht zu erkennen sein", s:"Der Nutzen liegt auf der Hand.", sec:"A" },
    { w:"beziehen, sich auf", a:"", g:"+ A", pos:"v", en:"to refer to", de:"einen Bezug zu etwas herstellen", s:"Die Studie bezieht sich auf ältere Patienten.", sec:"A" },
    { w:"aussprechen, sich für", a:"", g:"+ A", pos:"v", en:"to speak out in favour of", de:"öffentlich für etwas eintreten", s:"Die Mehrheit spricht sich für Telemedizin aus.", sec:"A" },
    { w:"einführen", a:"", pos:"v", en:"to introduce", de:"etwas Neues zum ersten Mal verwenden", s:"Die Klinik führt eine digitale Akte ein.", sec:"A" },
    { w:"sinnvoll", a:"", pos:"adj", en:"sensible, useful", de:"vernünftig und nützlich", s:"Eine Online-Beratung ist bei Routinefragen sinnvoll.", sec:"A" },
    { w:"mithilfe von", a:"", g:"+ D", pos:"phr", en:"with the help of", de:"mit Unterstützung von etwas", s:"Mithilfe von Apps kann man Werte selbst messen.", sec:"A" },
    { w:"allerdings", a:"", pos:"adv", en:"however, though", de:"drückt eine Einschränkung aus", s:"Die App ist praktisch, allerdings nicht immer sicher.", sec:"A" },
    // B — Jobmesse
    { w:"Plattform", a:"die", pl:"-en", pos:"n", en:"platform", de:"ein Ort (oft im Internet), wo Angebot und Nachfrage zusammenkommen", s:"Auf der Plattform stellen sich viele Firmen vor.", sec:"B", c:"Internetplattform" },
    { w:"Event", a:"das", pl:"-s", pos:"n", en:"event", de:"eine besondere Veranstaltung", s:"Das Event zog Hunderte Besucher an.", sec:"B" },
    { w:"Veranstaltung", a:"die", pl:"-en", pos:"n", en:"event, function", de:"ein organisiertes Treffen mit einem Programm", s:"Die Veranstaltung findet in der Messehalle statt.", sec:"B" },
    { w:"Tagung", a:"die", pl:"-en", pos:"n", en:"conference", de:"ein Fachtreffen mit Vorträgen", s:"Auf der Tagung ging es um digitale Medizin.", sec:"B" },
    { w:"Meeting", a:"das", pl:"-s", pos:"n", en:"meeting", de:"ein geschäftliches Treffen", s:"Das Meeting wurde auf morgen verschoben.", sec:"B" },
    { w:"Location", a:"die", pl:"-s", pos:"n", en:"venue, location", de:"der Ort, an dem etwas stattfindet", s:"Wir suchen noch eine passende Location für die Messe.", sec:"B", c:"Eventlocation" },
    { w:"Buchung", a:"die", pl:"-en", pos:"n", en:"booking, reservation", de:"das feste Reservieren von etwas", s:"Die Buchung des Standes ist bereits bestätigt.", sec:"B" },
    { w:"Messe", a:"die", pl:"-n", pos:"n", en:"trade fair", de:"eine große Ausstellung, auf der Firmen ihre Angebote zeigen", s:"Auf der Messe suchen Firmen neue Mitarbeiter.", sec:"B", c:"Recruiting-Messe" },
    { w:"Präsentation", a:"die", pl:"-en", pos:"n", en:"presentation", de:"das Vorstellen von etwas vor Publikum", s:"Ihre Präsentation über das Startup war überzeugend.", sec:"B" },
    { w:"präsentieren", a:"", pos:"v", en:"to present", de:"etwas vor anderen vorstellen", s:"Das Team präsentiert seine Geschäftsidee.", sec:"B" },
    { w:"Geschäftsidee", a:"die", pl:"-n", pos:"n", en:"business idea", de:"eine Idee, mit der man Geld verdienen will", s:"Aus einer guten Geschäftsidee wurde eine Firma.", sec:"B" },
    { w:"Hintergrund", a:"der", pl:"¨e", pos:"n", en:"background", de:"die Umstände oder Vorgeschichte einer Sache", s:"Sie erklärte den Hintergrund der Gründung.", sec:"B" },
    { w:"Gründung", a:"die", pl:"-en", pos:"n", en:"founding, establishment", de:"das Ins-Leben-Rufen einer Firma", s:"Seit der Gründung ist die Firma stark gewachsen.", sec:"B" },
    { w:"Gründer", a:"der", pl:"-", pos:"n", en:"founder (m)", de:"eine Person, die eine Firma gegründet hat", s:"Der Gründer stellte sein Unternehmen vor.", sec:"B", c:"die Gründerin, -nen" },
    { w:"Ausstattung", a:"die", pl:"-en", pos:"n", en:"equipment, facilities", de:"alles, was zu etwas an Einrichtung gehört", s:"Die Ausstattung des Messestandes war modern.", sec:"B" },
    { w:"Bewirtung", a:"die", pl:"-en", pos:"n", en:"catering, hospitality", de:"das Versorgen von Gästen mit Essen und Trinken", s:"Für die Bewirtung der Gäste sorgt ein Caterer.", sec:"B" },
    { w:"benötigen", a:"", pos:"v", en:"to need, to require", de:"brauchen", s:"Für den Stand benötigen wir Strom und Internet.", sec:"B" },
    { w:"recherchieren", a:"", pos:"v", en:"to research", de:"gezielt nach Informationen suchen", s:"Vor der Messe recherchiere ich die Firmen.", sec:"B" },
    { w:"zeitintensiv", a:"", pos:"adj", en:"time-consuming", de:"viel Zeit kostend", s:"Die Vorbereitung der Messe ist zeitintensiv.", sec:"B" },
    { w:"Konzept", a:"das", pl:"-e", pos:"n", en:"concept", de:"ein durchdachter Plan", s:"Das Konzept des Startups überzeugte die Jury.", sec:"B" },
    { w:"Service", a:"der", pl:"-s", pos:"n", en:"service", de:"eine Dienstleistung für Kunden", s:"Ein guter Service bindet die Kunden.", sec:"B", c:"Zusatzservice" },
    { w:"nutzen", a:"", pos:"v", en:"to use", de:"etwas verwenden, um einen Vorteil zu haben", s:"Wir nutzen die Messe, um Kontakte zu knüpfen.", sec:"B" },
    { w:"auswählen", a:"", pos:"v", en:"to select, to choose", de:"aus mehreren Dingen eines aussuchen", s:"Die Firma wählt die besten Bewerber aus.", sec:"B" },
    { w:"passend", a:"", pos:"adj", en:"suitable, matching", de:"gut geeignet für einen Zweck", s:"Wir suchen passende Mitarbeiter für das Team.", sec:"B" },
    { w:"Privatperson", a:"die", pl:"-en", pos:"n", en:"private individual", de:"eine einzelne Person, keine Firma", s:"Auch Privatpersonen dürfen die Messe besuchen.", sec:"B" },
    { w:"Entwicklung", a:"die", pl:"-en", pos:"n", en:"development", de:"die Veränderung über die Zeit", s:"Die Entwicklung des Unternehmens verlief rasant.", sec:"B" },
    { w:"weiterentwickeln, sich", a:"", pos:"v", en:"to develop further", de:"sich verbessern und weiter wachsen", s:"Die Firma will sich ständig weiterentwickeln.", sec:"B" },
    { w:"erweitern", a:"", pos:"v", en:"to expand, to extend", de:"größer machen, mehr hinzufügen", s:"Sie wollen das Angebot erweitern.", sec:"B", c:"das Angebot erweitern" },
    { w:"ausweiten", a:"", pos:"v", en:"to expand, to widen", de:"auf einen größeren Bereich vergrößern", s:"Das Startup weitet sein Geschäft auf Europa aus.", sec:"B" },
    { w:"ausbauen", a:"", pos:"v", en:"to build up, to expand", de:"stärker und größer machen", s:"Sie bauen ihre Marktposition weiter aus.", sec:"B" },
    { w:"Ausbau", a:"der", pl:"—", g:"hier nur Sg.", pos:"n", en:"expansion, extension", de:"das Vergrößern und Stärken von etwas", s:"Der Ausbau des Vertriebs kostet viel Geld.", sec:"B" },
    { w:"aufnehmen", a:"", pos:"v", en:"to take on, to include", de:"etwas neu ins Programm oder Team holen", s:"Wir nehmen zwei neue Produkte ins Programm auf.", sec:"B", c:"ins Programm aufnehmen" },
    { w:"expandieren", a:"", pos:"v", en:"to expand (a business)", de:"als Firma wachsen und sich vergrößern", s:"Das Unternehmen expandiert ins Ausland.", sec:"B" },
    { w:"Catering", a:"das", pl:"-s", pos:"n", en:"catering", de:"der Service, der Essen und Trinken liefert", s:"Das Catering auf der Messe war ausgezeichnet.", sec:"B" },
    { w:"Dienstleister", a:"der", pl:"-", pos:"n", en:"service provider", de:"eine Firma, die eine Dienstleistung anbietet", s:"Ein externer Dienstleister organisiert den Stand.", sec:"B" },
    { w:"Suche", a:"die", pl:"-n", pos:"n", en:"search", de:"das Suchen nach etwas", s:"Die Suche nach Fachkräften ist schwierig.", sec:"B" },
    { w:"engagiert", a:"", pos:"adj", en:"committed, dedicated", de:"mit großem Einsatz bei der Sache", s:"Sie sucht engagierte Mitarbeiter.", sec:"B" },
    { w:"Wachstum", a:"das", pl:"—", g:"nur Sg.", pos:"n", en:"growth", de:"das Größer- oder Mehr-Werden", s:"Das Wachstum der Firma war beeindruckend.", sec:"B" },
    { w:"mitgestalten", a:"", pos:"v", en:"to help shape", de:"aktiv an der Gestaltung von etwas teilnehmen", s:"Neue Mitarbeiter können die Zukunft mitgestalten.", sec:"B" },
    { w:"Sales-Team", a:"das", pl:"-s", pos:"n", en:"sales team", de:"die Gruppe von Mitarbeitern, die verkauft", s:"Das Sales-Team betreut die Kunden persönlich.", sec:"B" },
    { w:"Bestandskunde", a:"der", pl:"-n", pos:"n", en:"existing customer", de:"ein Kunde, den man schon länger hat", s:"Man muss auch die Bestandskunden gut pflegen.", sec:"B", c:"Bestandskunden pflegen" },
    { w:"Marketing", a:"das", pl:"—", g:"nur Sg.", pos:"n", en:"marketing", de:"alle Maßnahmen, um Produkte bekannt zu machen und zu verkaufen", s:"Gutes Marketing steigert den Umsatz.", sec:"B" },
    { w:"Bekanntheit", a:"die", pl:"-en", pos:"n", en:"level of recognition, fame", de:"das Bekanntsein bei vielen Menschen", s:"Die Messe erhöht die Bekanntheit der Marke.", sec:"B" },
    { w:"Internetpräsenz", a:"die", pl:"-en", pos:"n", en:"web presence", de:"der Auftritt einer Firma im Internet", s:"Eine gute Internetpräsenz ist heute unverzichtbar.", sec:"B" },
    { w:"Zielgruppe", a:"die", pl:"-n", pos:"n", en:"target group", de:"die Menschen, die man erreichen will", s:"Junge Leute sind ihre wichtigste Zielgruppe.", sec:"B" },
    { w:"bekommen etw. aus einer Hand", a:"", pos:"phr", en:"to get sth from a single source", de:"alles von einem einzigen Anbieter bekommen", s:"Beim Full-Service bekommt man alles aus einer Hand.", sec:"B" },
    { w:"motivieren", a:"", pos:"v", en:"to motivate", de:"jemandem Lust und Antrieb geben", s:"Ein gutes Team motiviert alle Mitarbeiter.", sec:"B" },
    { w:"erfolgreich", a:"", pos:"adj", en:"successful", de:"mit gutem Ergebnis, Erfolg habend", s:"Das Startup war schon im ersten Jahr erfolgreich.", sec:"B" },
    // C — Das digitale Zuhause
    { w:"Smart Home", a:"das", pl:"—", g:"nur Sg.", pos:"n", en:"smart home", de:"ein Zuhause mit vernetzter, steuerbarer Technik", s:"Im Smart Home steuert man das Licht per App.", sec:"C" },
    { w:"smart", a:"", pos:"adj", en:"smart", de:"intelligent und vernetzt (Technik)", s:"Der Lautsprecher ist smart und hört auf Sprache.", sec:"C" },
    { w:"Smartphone", a:"das", pl:"-s", pos:"n", en:"smartphone", de:"ein Handy mit Computerfunktionen", s:"Mit dem Smartphone steuere ich die Heizung.", sec:"C" },
    { w:"steuern", a:"", pos:"v", en:"to control, to steer", de:"etwas lenken oder regeln", s:"Die App steuert alle Geräte im Haus.", sec:"C" },
    { w:"kontrollieren", a:"", pos:"v", en:"to control, to check", de:"etwas prüfen oder überwachen", s:"Ich kontrolliere die Kameras vom Handy aus.", sec:"C" },
    { w:"überwachen", a:"", pos:"v", en:"to monitor, to surveil", de:"etwas ständig beobachten und kontrollieren", s:"Sensoren überwachen die Fenster und Türen.", sec:"C" },
    { w:"Überwachung", a:"die", pl:"-en", pos:"n", en:"surveillance, monitoring", de:"das ständige Beobachten und Kontrollieren", s:"Zu viel Überwachung gefährdet die Privatsphäre.", sec:"C" },
    { w:"Sensor", a:"der", pl:"-en", pos:"n", en:"sensor", de:"ein Gerät, das etwas misst oder erkennt", s:"Ein Sensor meldet, wenn sich ein Fenster öffnet.", sec:"C" },
    { w:"Verbrauch", a:"der", pl:"—", g:"hier nur Sg.", pos:"n", en:"consumption", de:"die Menge, die man von etwas nutzt (z. B. Strom)", s:"Das Smart Home senkt den Stromverbrauch.", sec:"C" },
    { w:"Einsparung", a:"die", pl:"-en", pos:"n", en:"saving", de:"das Weniger-Verbrauchen und Sparen von etwas", s:"Die Einsparung von Energie schont die Umwelt.", sec:"C" },
    { w:"Einbruch", a:"der", pl:"¨e", pos:"n", en:"burglary, break-in", de:"das gewaltsame Eindringen, um zu stehlen", s:"Eine Alarmanlage schützt vor Einbruch.", sec:"C" },
    { w:"Einbrecher", a:"der", pl:"-", pos:"n", en:"burglar", de:"eine Person, die in Häuser einbricht", s:"Die Kamera hat den Einbrecher aufgenommen.", sec:"C" },
    { w:"Brand", a:"der", pl:"¨e", pos:"n", en:"fire", de:"ein großes, gefährliches Feuer", s:"Ein Rauchmelder warnt früh vor einem Brand.", sec:"C" },
    { w:"Nutzung", a:"die", pl:"-en", pos:"n", en:"use, usage", de:"das Verwenden von etwas", s:"Die Nutzung smarter Geräte nimmt zu.", sec:"C" },
    { w:"hinterlassen", a:"", pos:"v", en:"to leave (behind)", de:"etwas zurücklassen, das bleibt", s:"Im Netz hinterlässt man viele persönliche Daten.", sec:"C", c:"seine Daten im Netz hinterlassen" },
    { w:"hacken", a:"", pos:"v", en:"to hack", de:"unerlaubt in ein Computersystem eindringen", s:"Kriminelle können schlecht gesicherte Geräte hacken.", sec:"C" },
    { w:"missbrauchen", a:"", pos:"v", en:"to misuse, to abuse", de:"etwas falsch oder schädlich verwenden", s:"Persönliche Daten werden manchmal missbraucht.", sec:"C", c:"Daten missbrauchen" },
    { w:"Anschaffung", a:"die", pl:"-en", pos:"n", en:"purchase, acquisition", de:"das Kaufen von etwas Größerem", s:"Die Anschaffung der Technik ist zunächst teuer.", sec:"C" },
    { w:"zum Schutz beitragen", a:"", pos:"phr", en:"to contribute to protection", de:"mithelfen, dass etwas geschützt ist", s:"Sensoren tragen zum Schutz des Hauses bei.", sec:"C" },
    { w:"Bequemlichkeit", a:"die", pl:"-en", pos:"n", en:"comfort, convenience", de:"das angenehme, bequeme Leben", s:"Viele schätzen die Bequemlichkeit eines Smart Homes.", sec:"C" },
    { w:"bedenken", a:"", pos:"v", en:"to consider, to bear in mind", de:"über etwas gründlich nachdenken", s:"Man sollte auch die Risiken bedenken.", sec:"C" },
    { w:"Argumentation", a:"die", pl:"-en", pos:"n", en:"line of argument", de:"die Art, wie man Argumente aufbaut", s:"Seine Argumentation gegen das Smart Home war überzeugend.", sec:"C" },
    // D — Telemedizin: Für und Wider im Video
    { w:"vernetzen", a:"", pos:"v", en:"to network, to connect", de:"Geräte oder Menschen miteinander verbinden", s:"Das System vernetzt Arzt, Patient und Klinik.", sec:"D" },
    { w:"Steuerung", a:"die", pl:"-en", pos:"n", en:"control (system)", de:"das Lenken und Regeln von Geräten", s:"Die Steuerung der Geräte erfolgt zentral.", sec:"D" },
    { w:"senken", a:"", pos:"v", en:"to lower, to reduce", de:"niedriger oder kleiner machen", s:"Telemedizin kann die Kosten senken.", sec:"D" },
    { w:"Tablet", a:"das", pl:"-s", pos:"n", en:"tablet", de:"ein flacher Computer zum Bedienen mit dem Finger", s:"Die Ärztin zeigt die Werte auf dem Tablet.", sec:"D" },
    { w:"umweltbewusst", a:"", pos:"adj", en:"environmentally conscious", de:"so, dass man auf die Umwelt achtet", s:"Weniger Fahrten zum Arzt sind umweltbewusst.", sec:"D" }
  ]
};
