/* Lektion 1 — Wortschatz. w=word, a=article, pl=plural, g=note, pos, en, de(simple def), s(example), c(book collocation) */
window.DECK = window.DECK || { lessons: {} };
window.DECK.lessons[1] = {
  title: "Zur Sprache kommen",
  subtitle: "Lernen, Wissen & Handschrift",
  cards: [
    // A — Zur Sprache kommen
    { w:"Stoff", a:"der", pl:"—", g:"hier nur Sg.", pos:"n", en:"material, subject matter (to learn)", de:"das, was man lernen muss", s:"Vor der Prüfung muss ich noch viel Stoff wiederholen.", sec:"A", c:"den Stoff durchdenken" },
    { w:"durchdenken", a:"", pos:"v", en:"to think through", de:"über etwas genau und gründlich nachdenken", s:"Ich möchte den Plan in Ruhe durchdenken, bevor ich entscheide.", sec:"A", c:"den Stoff durchdenken" },
    { w:"zusammenfassen", a:"", pos:"v", en:"to summarize", de:"das Wichtigste kurz mit eigenen Worten sagen", s:"Kannst du den Text in drei Sätzen zusammenfassen?", sec:"A", c:"etw. mit eigenen Worten zusammenfassen" },
    { w:"konzentrieren, sich auf", a:"", g:"+ A", pos:"v", en:"to concentrate on", de:"die ganze Aufmerksamkeit auf eine Sache richten", s:"Beim Lernen konzentriere ich mich nur auf ein Thema.", sec:"A" },
    { w:"ordnen nach", a:"", g:"+ D", pos:"v", en:"to sort / arrange by", de:"Dinge in eine bestimmte Reihenfolge bringen", s:"Ich ordne die Vokabeln nach Themen.", sec:"A", c:"nach Farben ordnen" },
    { w:"aufschreiben", a:"", pos:"v", en:"to write down", de:"etwas auf Papier notieren", s:"Neue Wörter schreibe ich mir immer sofort auf.", sec:"A" },
    { w:"achten auf", a:"", g:"+ A", pos:"v", en:"to pay attention to", de:"auf etwas besonders aufpassen", s:"Beim Sprechen achte ich auf die richtige Aussprache.", sec:"A" },
    { w:"aufnehmen", a:"", pos:"v", en:"to record (audio/video)", de:"Ton oder Bild mit einem Gerät speichern", s:"Ich nehme die Wörter mit dem Handy auf und höre sie unterwegs.", sec:"A", c:"mit dem Handy aufnehmen" },
    { w:"nachsprechen", a:"", pos:"v", en:"to repeat (after sb)", de:"etwas laut wiederholen, das man gehört hat", s:"Hören Sie den Satz und sprechen Sie ihn nach.", sec:"A" },
    { w:"anwenden", a:"", pos:"v", en:"to apply, to use", de:"etwas Gelerntes praktisch benutzen", s:"Grammatik versteht man erst, wenn man sie anwendet.", sec:"A", c:"etw. praktisch anwenden" },
    { w:"bewegen, sich", a:"", pos:"v", en:"to move (oneself)", de:"den Körper aktiv sein lassen, in Bewegung sein", s:"Beim Lernen hilft es mir, mich zwischendurch zu bewegen.", sec:"A" },
    { w:"Sprachkenntnisse", a:"die", pl:"", g:"nur Pl.", pos:"n", en:"language skills / knowledge", de:"das, was man in einer Sprache kann", s:"Für den Job braucht man gute Sprachkenntnisse in Deutsch.", sec:"A", c:"Sprachkenntnisse erwerben" },
    { w:"Aussage", a:"die", pl:"-n", pos:"n", en:"statement", de:"das, was jemand sagt oder behauptet", s:"Seine Aussage hat mich überzeugt.", sec:"A" },
    { w:"begründen", a:"", pos:"v", en:"to justify, to give reasons", de:"sagen, warum etwas so ist", s:"Kannst du deine Meinung genauer begründen?", sec:"A" },
    { w:"zustimmen", a:"", pos:"v", en:"to agree", de:"sagen, dass man die gleiche Meinung hat", s:"Ich stimme dir völlig zu.", sec:"A" },
    { w:"Widerspruch", a:"der", pl:"¨e", pos:"n", en:"contradiction, objection", de:"eine Aussage, die das Gegenteil sagt", s:"Zwischen seinen Worten und Taten gibt es einen Widerspruch.", sec:"A", c:"Widerspruch ausdrücken" },
    { w:"Ansicht", a:"die", pl:"-en", pos:"n", en:"view, opinion", de:"die Meinung, die man zu etwas hat", s:"Meiner Ansicht nach ist Übung am wichtigsten.", sec:"A", c:"der Ansicht sein" },
    // B — Auf dem Weg zum Wissen
    { w:"Forum", a:"das", pl:"Foren", pos:"n", en:"forum", de:"ein Ort im Internet, wo man Fragen stellt und diskutiert", s:"Im Forum habe ich eine gute Antwort auf meine Frage bekommen.", sec:"B" },
    { w:"Beitrag", a:"der", pl:"¨e", pos:"n", en:"post, contribution", de:"ein Text, den man z. B. in einem Forum schreibt", s:"Ihr Beitrag im Forum war sehr hilfreich.", sec:"B" },
    { w:"Vorbereitung", a:"die", pl:"-en", pos:"n", en:"preparation", de:"alles, was man vorher für etwas tut", s:"Die Vorbereitung auf die Prüfung dauert Wochen.", sec:"B" },
    { w:"Vorschlag", a:"der", pl:"¨e", pos:"n", en:"suggestion, proposal", de:"eine Idee, die man anderen anbietet", s:"Ich habe einen Vorschlag: Lernen wir zusammen?", sec:"B" },
    { w:"Alternative", a:"die", pl:"-n", pos:"n", en:"alternative", de:"eine andere Möglichkeit", s:"Als Alternative zum Buch nutze ich eine App.", sec:"B" },
    { w:"Lerntechnik", a:"die", pl:"-en", pos:"n", en:"learning technique", de:"eine bestimmte Methode, um zu lernen", s:"Karteikarten sind eine bewährte Lerntechnik.", sec:"B" },
    { w:"Lernmethode", a:"die", pl:"-n", pos:"n", en:"learning method", de:"eine Art und Weise, wie man lernt", s:"Jeder muss seine eigene Lernmethode finden.", sec:"B" },
    { w:"Lerngruppe", a:"die", pl:"-n", pos:"n", en:"study group", de:"mehrere Personen, die zusammen lernen", s:"In der Lerngruppe erklären wir uns den Stoff gegenseitig.", sec:"B" },
    { w:"Lernplan", a:"der", pl:"¨e", pos:"n", en:"study plan", de:"ein Plan, der zeigt, wann man was lernt", s:"Mit einem Lernplan verliere ich nicht den Überblick.", sec:"B" },
    { w:"Lernstil", a:"der", pl:"-e", pos:"n", en:"learning style", de:"die Art, wie jemand am besten lernt", s:"Mein Lernstil ist eher visuell.", sec:"B" },
    { w:"Lerntipp", a:"der", pl:"-s", pos:"n", en:"study tip", de:"ein guter Rat zum Lernen", s:"Hast du einen Lerntipp gegen Prüfungsstress?", sec:"B" },
    { w:"Lernerfahrung", a:"die", pl:"-en", pos:"n", en:"learning experience", de:"das, was man beim Lernen erlebt hat", s:"Aus dieser Lernerfahrung habe ich viel gelernt.", sec:"B" },
    { w:"Lerntyp", a:"der", pl:"-en", pos:"n", en:"type of learner", de:"die Kategorie, zu der ein Lernender gehört", s:"Als auditiver Lerntyp höre ich gern Podcasts.", sec:"B" },
    { w:"Methodenmix", a:"der", pl:"-e", pos:"n", en:"mix of methods", de:"die Kombination verschiedener Methoden", s:"Ein Methodenmix hält das Lernen abwechslungsreich.", sec:"B" },
    { w:"auditiv", a:"", pos:"adj", en:"auditory", de:"über das Hören", s:"Auditiv lerne ich am besten mit Hörtexten.", sec:"B" },
    { w:"visuell", a:"", pos:"adj", en:"visual", de:"über das Sehen", s:"Visuelle Lerner arbeiten gern mit Bildern.", sec:"B" },
    { w:"veraltet", a:"", pos:"adj", en:"outdated", de:"nicht mehr modern, alt", s:"Diese Lernmethode gilt heute als veraltet.", sec:"B" },
    { w:"Studie", a:"die", pl:"-n", pos:"n", en:"study, research", de:"eine wissenschaftliche Untersuchung", s:"Eine neue Studie zeigt, dass Pausen das Lernen verbessern.", sec:"B", c:"Studien ergeben" },
    { w:"auf Basis", a:"", g:"+ G / von", pos:"phr", en:"on the basis of", de:"mit etwas als Grundlage", s:"Auf Basis der Ergebnisse ändern wir den Plan.", sec:"B" },
    { w:"Rangfolge", a:"die", pl:"-n", pos:"n", en:"ranking, order", de:"eine Reihenfolge nach Wichtigkeit", s:"Die Methoden stehen in einer klaren Rangfolge.", sec:"B", c:"eine Rangfolge erstellen" },
    { w:"bewerten", a:"", pos:"v", en:"to evaluate, to rate", de:"sagen, wie gut oder schlecht etwas ist", s:"Die Forscher bewerten jede Methode einzeln.", sec:"B" },
    { w:"abschneiden", a:"", g:"gut / schlecht", pos:"v", en:"to fare, to perform (well/badly)", de:"ein bestimmtes Ergebnis erreichen", s:"Wiederholtes Lesen schneidet in Tests schlecht ab.", sec:"B" },
    { w:"überprüfen", a:"", pos:"v", en:"to check, to verify", de:"kontrollieren, ob etwas richtig ist", s:"Überprüfe deine Antworten noch einmal.", sec:"B" },
    { w:"empfehlenswert", a:"", pos:"adj", en:"recommendable", de:"so gut, dass man es empfehlen kann", s:"Diese App ist sehr empfehlenswert.", sec:"B" },
    { w:"hilfreich", a:"", pos:"adj", en:"helpful", de:"nützlich, so dass es hilft", s:"Deine Tipps waren wirklich hilfreich.", sec:"B" },
    { w:"effektiv", a:"", pos:"adj", en:"effective", de:"mit gutem Ergebnis, wirkungsvoll", s:"Kurze, tägliche Einheiten sind sehr effektiv.", sec:"B" },
    { w:"optimal", a:"", pos:"adj", en:"optimal, ideal", de:"so gut wie möglich", s:"Der Morgen ist für mich die optimale Lernzeit.", sec:"B" },
    { w:"gegenteilig", a:"", pos:"adj", en:"opposite", de:"genau umgekehrt", s:"Die Studie kam zu einem gegenteiligen Ergebnis.", sec:"B" },
    { w:"hervorheben", a:"", pos:"v", en:"to highlight, to emphasize", de:"etwas besonders wichtig zeigen", s:"Wichtige Wörter sollte man im Text hervorheben.", sec:"B" },
    { w:"markieren", a:"", pos:"v", en:"to mark, to highlight", de:"mit einer Farbe kennzeichnen", s:"Ich markiere die Schlüsselwörter gelb.", sec:"B" },
    { w:"unterstreichen", a:"", pos:"v", en:"to underline", de:"eine Linie unter ein Wort ziehen", s:"Unterstreiche die Verben im Satz.", sec:"B" },
    { w:"Vorwissen", a:"das", pl:"—", g:"nur Sg.", pos:"n", en:"prior knowledge", de:"das Wissen, das man schon vorher hat", s:"Ohne Vorwissen ist der Text schwer zu verstehen.", sec:"B" },
    { w:"einsteigen", a:"", pos:"v", en:"to get into (a topic)", de:"mit etwas anfangen, in ein Thema kommen", s:"Mit einem einfachen Beispiel steigen wir ins Thema ein.", sec:"B", c:"in ein Thema einsteigen" },
    { w:"Überblick", a:"der", pl:"-e", pos:"n", en:"overview", de:"ein allgemeines Bild vom Ganzen", s:"Die Tabelle gibt einen guten Überblick.", sec:"B" },
    { w:"überfliegen", a:"", pos:"v", en:"to skim (read)", de:"einen Text schnell und grob lesen", s:"Ich überfliege den Artikel zuerst kurz.", sec:"B" },
    { w:"global", a:"", pos:"adj", en:"global (reading for gist)", de:"das Ganze grob erfassend", s:"Beim globalen Lesen sucht man die Hauptidee.", sec:"B" },
    { w:"selektiv", a:"", pos:"adj", en:"selective", de:"gezielt nur bestimmte Informationen", s:"Selektives Lesen spart viel Zeit.", sec:"B" },
    { w:"Kerninformation", a:"die", pl:"-en", pos:"n", en:"core information", de:"die wichtigste Information", s:"Notiere nur die Kerninformationen.", sec:"B" },
    { w:"nachdenken über", a:"", g:"+ A", pos:"v", en:"to think about", de:"sich Gedanken über etwas machen", s:"Ich denke oft über meine Lernziele nach.", sec:"B" },
    { w:"Zusammenhang", a:"der", pl:"¨e", pos:"n", en:"connection, context", de:"die Verbindung zwischen zwei Dingen", s:"Man muss den Zusammenhang zwischen den Ideen verstehen.", sec:"B" },
    { w:"wiedergeben", a:"", pos:"v", en:"to reproduce, to render", de:"etwas mit eigenen Worten noch einmal sagen", s:"Gib den Inhalt des Textes kurz wieder.", sec:"B" },
    { w:"abfragen", a:"", g:"jdn. / s. gegenseitig", pos:"v", en:"to quiz, to test", de:"jemandem Fragen zum Stoff stellen", s:"Meine Freundin fragt mich die Vokabeln ab.", sec:"B" },
    { w:"behalten", a:"", pos:"v", en:"to retain, to remember", de:"im Gedächtnis speichern, nicht vergessen", s:"Mit Bildern behalte ich neue Wörter besser.", sec:"B", c:"den Stoff / Wörter behalten" },
    { w:"Gedächtnis", a:"das", pl:"-se", pos:"n", en:"memory", de:"die Fähigkeit, sich an Dinge zu erinnern", s:"Sie hat ein sehr gutes Gedächtnis.", sec:"B", c:"Langzeitgedächtnis" },
    { w:"Sinnesorgan", a:"das", pl:"-e", pos:"n", en:"sensory organ", de:"ein Organ zum Wahrnehmen (Auge, Ohr …)", s:"Augen und Ohren sind wichtige Sinnesorgane.", sec:"B" },
    { w:"aufnehmen", a:"", pos:"v", en:"to absorb, to take in (knowledge)", de:"neues Wissen ins Gehirn bringen", s:"Am Morgen nehme ich Neues leichter auf.", sec:"B", c:"Wissen aufnehmen" },
    { w:"verknüpfen mit", a:"", g:"+ D", pos:"v", en:"to link / connect with", de:"zwei Dinge miteinander verbinden", s:"Ich verknüpfe neue Wörter mit Bildern.", sec:"B" },
    { w:"aufteilen", a:"", g:"in Portionen", pos:"v", en:"to divide up", de:"etwas in kleinere Teile teilen", s:"Ich teile den Stoff in kleine Portionen auf.", sec:"B" },
    { w:"regelmäßig", a:"", pos:"adj", en:"regular(ly)", de:"immer wieder in gleichen Abständen", s:"Wer regelmäßig übt, macht schnelle Fortschritte.", sec:"B" },
    { w:"abhaken", a:"", pos:"v", en:"to tick / check off", de:"Erledigtes auf einer Liste markieren", s:"Jede fertige Aufgabe hake ich zufrieden ab.", sec:"B" },
    { w:"Erfolgserlebnis", a:"das", pl:"-se", pos:"n", en:"sense of achievement", de:"das gute Gefühl, wenn man etwas geschafft hat", s:"Kleine Erfolgserlebnisse motivieren beim Lernen.", sec:"B" },
    { w:"beherrschen", a:"", pos:"v", en:"to master", de:"etwas sehr gut können", s:"Nach Wochen beherrsche ich die Grammatik endlich.", sec:"B", c:"den Stoff beherrschen" },
    { w:"aufschieben", a:"", pos:"v", en:"to postpone, to put off", de:"etwas auf später verschieben", s:"Schieb das Lernen nicht immer auf!", sec:"B" },
    { w:"ängstlich", a:"", pos:"adj", en:"anxious, fearful", de:"voller Angst", s:"Vor Prüfungen bin ich oft ängstlich.", sec:"B" },
    { w:"leicht / schwer fallen", a:"", pos:"phr", en:"to be easy / hard (for sb)", de:"einfach oder schwierig für jemanden sein", s:"Sprachen lernen fällt mir leicht.", sec:"B", c:"Es fällt mir leicht / schwer." },
    { w:"Behauptung", a:"die", pl:"-en", pos:"n", en:"claim, assertion", de:"eine Aussage, die man für wahr hält (ohne Beweis)", s:"Diese Behauptung kann man nicht beweisen.", sec:"B" },
    // C — Mit der Hand schreiben – wozu?
    { w:"Zeitalter", a:"das", pl:"-", pos:"n", en:"era, age", de:"ein langer, besonderer Zeitabschnitt", s:"Wir leben im digitalen Zeitalter.", sec:"C" },
    { w:"Forschung", a:"die", pl:"-en", pos:"n", en:"research", de:"die wissenschaftliche Suche nach neuem Wissen", s:"Die Forschung untersucht, wie das Gehirn lernt.", sec:"C" },
    { w:"Neurowissenschaft", a:"die", pl:"-en", pos:"n", en:"neuroscience", de:"die Wissenschaft vom Gehirn und Nervensystem", s:"Die Neurowissenschaft erklärt, wie wir uns erinnern.", sec:"C" },
    { w:"Rückgang", a:"der", pl:"¨e", pos:"n", en:"decline, decrease", de:"das Weniger-Werden von etwas", s:"Man beobachtet einen Rückgang der Handschrift.", sec:"C" },
    { w:"Ergonomie", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"ergonomics", de:"die Anpassung von Geräten an den Menschen", s:"Beim Sitzen am Schreibtisch ist gute Ergonomie wichtig.", sec:"C" },
    { w:"Motorik", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"motor skills", de:"die Fähigkeit, Bewegungen zu steuern", s:"Schreiben mit der Hand trainiert die Motorik.", sec:"C" },
    { w:"Schrift", a:"die", pl:"-en", pos:"n", en:"script, handwriting", de:"die Art, wie Buchstaben geschrieben werden", s:"Ihre Schrift ist schön und gut lesbar.", sec:"C", c:"Druckschrift, Schreibschrift, Handschrift" },
    { w:"schriftlich / handschriftlich", a:"", pos:"adj", en:"written / handwritten", de:"auf Papier bzw. mit der Hand geschrieben", s:"Bitte machen Sie sich handschriftliche Notizen.", sec:"C" },
    { w:"Schreiben mit der Hand", a:"das", pl:"—", pos:"n", en:"writing by hand", de:"das Benutzen eines Stifts statt einer Tastatur", s:"Das Schreiben mit der Hand hilft dem Gedächtnis.", sec:"C" },
    { w:"Handschreiben", a:"das", pl:"—", g:"nur Sg.", pos:"n", en:"handwriting (the act)", de:"das Schreiben mit der Hand", s:"Das Handschreiben wird in der Schule seltener geübt.", sec:"C" },
    { w:"flüssig", a:"", g:"(schreiben)", pos:"adj", en:"fluent, smooth", de:"ohne Stocken, gleichmäßig", s:"Nach viel Übung schreibe ich flüssig.", sec:"C" },
    { w:"benötigen", a:"", pos:"v", en:"to need, to require", de:"brauchen", s:"Für die Übung benötigst du nur Papier und Stift.", sec:"C" },
    { w:"lehren", a:"", pos:"v", en:"to teach", de:"jemandem etwas beibringen", s:"Sie lehrt Deutsch an der Universität.", sec:"C" },
    { w:"Erlernen", a:"das", pl:"—", g:"nur Sg.", pos:"n", en:"the learning (of sth)", de:"der Vorgang, etwas zu lernen", s:"Das Erlernen einer Sprache braucht Zeit.", sec:"C" },
    { w:"Abschaffung", a:"die", pl:"-en", pos:"n", en:"abolition", de:"das Beenden oder Entfernen von etwas", s:"Viele diskutieren über die Abschaffung der Schreibschrift.", sec:"C" },
    { w:"abschaffen", a:"", pos:"v", en:"to abolish, to get rid of", de:"etwas beenden, nicht mehr benutzen", s:"Manche Schulen wollen die Handschrift abschaffen.", sec:"C" },
    { w:"Tastatur", a:"die", pl:"-en", pos:"n", en:"keyboard", de:"die Tasten, mit denen man am Computer tippt", s:"Auf einer deutschen Tastatur liegt das Z anders.", sec:"C" },
    { w:"tippen", a:"", pos:"v", en:"to type", de:"mit den Fingern auf einer Tastatur schreiben", s:"Ich tippe schneller, als ich mit der Hand schreibe.", sec:"C" },
    { w:"Tippen", a:"das", pl:"—", g:"nur Sg.", pos:"n", en:"typing", de:"das Schreiben auf der Tastatur", s:"Beim Tippen macht man leicht Flüchtigkeitsfehler.", sec:"C" },
    { w:"Wirkung", a:"die", pl:"-en", pos:"n", en:"effect", de:"das, was etwas bewirkt oder auslöst", s:"Handschrift hat eine positive Wirkung auf das Lernen.", sec:"C" },
    { w:"Gehirn", a:"das", pl:"-e", pos:"n", en:"brain", de:"das Organ im Kopf zum Denken", s:"Das Gehirn verarbeitet ständig Informationen.", sec:"C" },
    { w:"Gehirnaktivität", a:"die", pl:"-en", pos:"n", en:"brain activity", de:"die Arbeit oder Tätigkeit im Gehirn", s:"Beim Schreiben steigt die Gehirnaktivität.", sec:"C" },
    { w:"Gehirnareal", a:"das", pl:"-e", pos:"n", en:"brain area / region", de:"ein bestimmter Bereich im Gehirn", s:"Verschiedene Gehirnareale sind für Sprache zuständig.", sec:"C" },
    { w:"Bereich", a:"der", pl:"-e", pos:"n", en:"area, field", de:"ein bestimmter Teil oder ein Themengebiet", s:"In diesem Bereich kenne ich mich gut aus.", sec:"C" },
    { w:"aktivieren", a:"", pos:"v", en:"to activate", de:"etwas in Gang bringen, aktiv machen", s:"Musik kann das Gehirn aktivieren.", sec:"C" },
    { w:"wiedererkennen", a:"", pos:"v", en:"to recognize (again)", de:"etwas Bekanntes erneut erkennen", s:"Ich erkenne das Wort wieder, weiß aber die Bedeutung nicht.", sec:"C" },
    { w:"erinnern, sich an", a:"", g:"+ A", pos:"v", en:"to remember", de:"etwas aus der Vergangenheit im Kopf haben", s:"Ich erinnere mich gut an diese Regel.", sec:"C" },
    { w:"Verknüpfung", a:"die", pl:"-en", pos:"n", en:"link, connection", de:"eine Verbindung zwischen Informationen", s:"Gute Verknüpfungen helfen dem Gedächtnis.", sec:"C" },
    { w:"Verbindung", a:"die", pl:"-en", pos:"n", en:"connection", de:"das, was zwei Dinge zusammenbringt", s:"Es gibt eine klare Verbindung zwischen Schlaf und Lernen.", sec:"C" },
    { w:"Speicher", a:"der", pl:"-", pos:"n", en:"storage, memory", de:"der Ort, wo etwas gespeichert wird", s:"Das Langzeitgedächtnis ist unser wichtigster Speicher.", sec:"C" },
    { w:"extern", a:"", pos:"adj", en:"external", de:"von außen, nicht im Inneren", s:"Ich sichere die Daten auf einer externen Festplatte.", sec:"C" },
    { w:"verarbeiten", a:"", pos:"v", en:"to process", de:"Informationen aufnehmen und ordnen", s:"Im Schlaf verarbeitet das Gehirn das Gelernte.", sec:"C", c:"Informationen verarbeiten" },
    { w:"Gehörte", a:"das", pl:"—", pos:"n", en:"what was heard", de:"das, was man gehört hat", s:"Fassen Sie das Gehörte kurz zusammen.", sec:"C" },
    { w:"merken, sich", a:"", pos:"v", en:"to memorize, to note", de:"etwas im Gedächtnis behalten", s:"Diese Zahl kann ich mir gut merken.", sec:"C" },
    { w:"Notiz", a:"die", pl:"-en", pos:"n", en:"note", de:"eine kurze schriftliche Aufzeichnung", s:"Ich mache mir während des Vortrags Notizen.", sec:"C", c:"Notizen machen" },
    { w:"Notizblock", a:"der", pl:"¨e", pos:"n", en:"notepad", de:"ein kleines Heft für Notizen", s:"Ich habe immer einen Notizblock dabei.", sec:"C" },
    { w:"notieren", a:"", pos:"v", en:"to note down", de:"kurz aufschreiben", s:"Notieren Sie die wichtigsten Stichwörter.", sec:"C" },
    { w:"Vorlesung", a:"die", pl:"-en", pos:"n", en:"lecture", de:"ein Vortrag an der Universität", s:"Die Vorlesung beginnt um neun Uhr.", sec:"C" },
    { w:"mitschreiben", a:"", pos:"v", en:"to take notes (while listening)", de:"während man zuhört, mitschreiben", s:"In der Vorlesung schreibe ich fleißig mit.", sec:"C" },
    { w:"protokollieren", a:"", pos:"v", en:"to record, to take minutes", de:"den Verlauf schriftlich festhalten", s:"Wer protokolliert heute die Sitzung?", sec:"C" },
    { w:"Ergebnis", a:"das", pl:"-se", pos:"n", en:"result", de:"das, was am Ende herauskommt", s:"Das Ergebnis der Studie war überraschend.", sec:"C", c:"Studien ergeben" },
    { w:"ergeben", a:"", pos:"v", en:"to yield, to show (a result)", de:"als Resultat haben", s:"Die Untersuchung ergab klare Vorteile.", sec:"C", c:"Studien ergeben" },
    { w:"Inhalt", a:"der", pl:"-e", pos:"n", en:"content", de:"das, worüber ein Text handelt", s:"Fassen Sie den Inhalt des Artikels zusammen.", sec:"C" },
    { w:"intensiv", a:"", pos:"adj", en:"intensive", de:"sehr stark, mit viel Einsatz", s:"Vor der Prüfung lerne ich sehr intensiv.", sec:"C" },
    { w:"dauerhaft", a:"", pos:"adj", en:"lasting, permanent", de:"für lange Zeit bleibend", s:"Nur regelmäßiges Üben führt zu dauerhaftem Erfolg.", sec:"C" },
    { w:"Ausführung", a:"die", pl:"-en", pos:"n", en:"execution, version", de:"die Art, wie etwas gemacht wird", s:"Die genaue Ausführung der Aufgabe steht in der Anleitung.", sec:"C" },
    // D — In einer Lerngruppe oder allein?
    { w:"Wissen", a:"das", pl:"—", g:"nur Sg.", pos:"n", en:"knowledge", de:"alles, was man weiß", s:"Sein Wissen über Geschichte ist beeindruckend.", sec:"D", c:"Grundwissen, Faktenwissen, Wissen vertiefen" },
    { w:"Fakt", a:"der / das", pl:"-en", pos:"n", en:"fact", de:"eine sichere, wahre Information", s:"Das ist kein Fakt, sondern nur eine Meinung.", sec:"D" },
    { w:"Grundlage", a:"die", pl:"-n", pos:"n", en:"basis, foundation", de:"das, worauf etwas aufbaut", s:"Ein guter Wortschatz ist die Grundlage zum Sprechen.", sec:"D" },
    { w:"beitragen zu", a:"", g:"+ D", pos:"v", en:"to contribute to", de:"mithelfen, dass etwas entsteht", s:"Jeder kann zum Erfolg der Gruppe beitragen.", sec:"D", c:"in einer Gruppe zu etw. beitragen" },
    { w:"Diskussion", a:"die", pl:"-en", pos:"n", en:"discussion", de:"ein Gespräch mit verschiedenen Meinungen", s:"In der Diskussion vertrat jeder seinen Standpunkt.", sec:"D" },
    { w:"fleißig", a:"", g:"≠ faul", pos:"adj", en:"hard-working (≠ lazy)", de:"viel und gern arbeitend", s:"Sie ist eine fleißige Studentin.", sec:"D" },
    { w:"Kommunikationsfähigkeit", a:"die", pl:"-en", pos:"n", en:"communication skills", de:"die Fähigkeit, gut mit anderen zu reden", s:"Teamarbeit verbessert die Kommunikationsfähigkeit.", sec:"D" },
    { w:"Arbeitsweise", a:"die", pl:"-n", pos:"n", en:"way of working", de:"die Art, wie jemand arbeitet", s:"Jeder hat seine eigene Arbeitsweise.", sec:"D" },
    { w:"Zeitmanagement", a:"das", pl:"—", g:"nur Sg.", pos:"n", en:"time management", de:"das gute Einteilen der eigenen Zeit", s:"Gutes Zeitmanagement senkt den Stress.", sec:"D" },
    { w:"Einzelarbeit", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"individual work", de:"das Arbeiten allein", s:"Diese Aufgabe machen wir in Einzelarbeit.", sec:"D" },
    { w:"Gruppenarbeit", a:"die", pl:"-en", pos:"n", en:"group work", de:"das Arbeiten in einer Gruppe", s:"Gruppenarbeit macht mir mehr Spaß als Einzelarbeit.", sec:"D" },
    { w:"ermöglichen", a:"", pos:"v", en:"to make possible, to enable", de:"möglich machen", s:"Das Stipendium ermöglicht ihr ein Studium.", sec:"D" },
    { w:"Stellungnahme", a:"die", pl:"-n", pos:"n", en:"statement, position", de:"eine Äußerung der eigenen Meinung", s:"Er gab eine kurze Stellungnahme zum Thema ab.", sec:"D" },
    { w:"Einleitung", a:"die", pl:"-en", pos:"n", en:"introduction", de:"der erste Teil eines Textes", s:"In der Einleitung nennst du das Thema.", sec:"D" },
    { w:"Hauptteil", a:"der", pl:"-e", pos:"n", en:"main part", de:"der wichtigste, mittlere Teil", s:"Im Hauptteil bringst du deine Argumente.", sec:"D" },
    { w:"Schluss", a:"der", pl:"¨e", pos:"n", en:"conclusion, ending", de:"der letzte Teil eines Textes", s:"Am Schluss fasst du alles kurz zusammen.", sec:"D" },
    { w:"Fazit", a:"das", pl:"-s / -e", g:"meist Sg.", pos:"n", en:"conclusion, bottom line", de:"das zusammenfassende Ergebnis", s:"Mein Fazit: Übung ist am wichtigsten.", sec:"D" },
    { w:"Argument", a:"das", pl:"-e", pos:"n", en:"argument", de:"ein Grund für oder gegen etwas", s:"Dein Argument überzeugt mich.", sec:"D" },
    { w:"These", a:"die", pl:"-n", pos:"n", en:"thesis, claim", de:"eine Behauptung, die man begründet", s:"Er stellt die These auf, dass Handschrift besser sei.", sec:"D" },
    { w:"Vorteil", a:"der", pl:"-e", pos:"n", en:"advantage", de:"ein guter Punkt an einer Sache", s:"Ein Vorteil des Onlinelernens ist die Flexibilität.", sec:"D" },
    { w:"Nachteil", a:"der", pl:"-e", pos:"n", en:"disadvantage", de:"ein schlechter Punkt an einer Sache", s:"Der Nachteil ist, dass man sich allein motivieren muss.", sec:"D" }
  ]
};
