/* Lektion 3 — Wortschatz */
window.DECK = window.DECK || { lessons: {} };
window.DECK.lessons[3] = {
  title: "Lügen und Betrügen",
  subtitle: "Täuschung, Tierreich & Ehrlichkeit",
  cards: [
    // A — Lügen und Betrügen
    { w:"Lüge", a:"die", pl:"-n", pos:"n", en:"lie", de:"eine Aussage, die bewusst nicht wahr ist", s:"Eine kleine Lüge kann große Folgen haben.", sec:"A", c:"Notlüge" },
    { w:"Betrug", a:"der", pl:"—", g:"nur Sg.", pos:"n", en:"fraud, deception", de:"das absichtliche Täuschen, um einen Vorteil zu bekommen", s:"Der Betrug mit falschen Rechnungen flog schnell auf.", sec:"A", c:"Selbstbetrug" },
    { w:"betrügen", a:"", pos:"v", en:"to cheat, to deceive", de:"jemanden bewusst täuschen, um einen Vorteil zu haben", s:"Er hat seine Kunden jahrelang betrogen.", sec:"A" },
    { w:"flunkern", a:"", pos:"v", en:"to fib", de:"aus Spaß eine kleine, harmlose Lüge sagen", s:"Kinder flunkern manchmal, um Ärger zu vermeiden.", sec:"A" },
    { w:"schwindeln", a:"", pos:"v", en:"to fib, to tell fibs", de:"nicht ganz die Wahrheit sagen", s:"Bei seinem Alter hat er ein bisschen geschwindelt.", sec:"A" },
    { w:"schummeln", a:"", pos:"v", en:"to cheat (in games/tests)", de:"beim Spiel oder Test unerlaubt tricksen", s:"In der Prüfung darf man nicht schummeln.", sec:"A" },
    { w:"tricksen", a:"", pos:"v", en:"to use tricks", de:"mit einem Trick einen Vorteil erreichen", s:"Er hat bei den Regeln getrickst.", sec:"A" },
    { w:"Irreführung", a:"die", pl:"-en", pos:"n", en:"misleading, deception", de:"das absichtliche In-die-Irre-Führen", s:"Die Werbung wurde wegen Irreführung verboten.", sec:"A" },
    { w:"Täuschung", a:"die", pl:"-en", pos:"n", en:"deception, illusion", de:"das Erzeugen eines falschen Eindrucks", s:"Optische Täuschungen tricksen unser Auge aus.", sec:"A" },
    { w:"täuschen", a:"", pos:"v", en:"to deceive", de:"einen falschen Eindruck erzeugen", s:"Das freundliche Lächeln sollte uns täuschen.", sec:"A" },
    { w:"Fake News", a:"die", pl:"", g:"Pl.", pos:"n", en:"fake news", de:"falsche Nachrichten, die absichtlich verbreitet werden", s:"Im Internet verbreiten sich Fake News besonders schnell.", sec:"A" },
    { w:"manipulieren", a:"", pos:"v", en:"to manipulate", de:"jemanden heimlich beeinflussen", s:"Mit falschen Zahlen kann man Menschen manipulieren.", sec:"A" },
    { w:"fälschen", a:"", pos:"v", en:"to falsify, to forge", de:"etwas Echtes nachmachen, um zu täuschen", s:"Er hat die Unterschrift gefälscht.", sec:"A" },
    { w:"Plagiat", a:"das", pl:"-e", pos:"n", en:"plagiarism", de:"das Kopieren fremder Texte als eigene", s:"Die Arbeit wurde als Plagiat erkannt.", sec:"A" },
    { w:"Doping", a:"das", pl:"-s", pos:"n", en:"doping", de:"der verbotene Gebrauch von Mitteln im Sport", s:"Wegen Dopings wurde ihm die Medaille aberkannt.", sec:"A" },
    { w:"Halbwahrheit", a:"die", pl:"-en", pos:"n", en:"half-truth", de:"eine Aussage, die nur teilweise stimmt", s:"Er sagte nur Halbwahrheiten, um besser dazustehen.", sec:"A" },
    { w:"Beschönigung", a:"die", pl:"-en", pos:"n", en:"glossing over", de:"das Darstellen von etwas als besser, als es ist", s:"Das ist keine Erklärung, sondern eine Beschönigung.", sec:"A" },
    { w:"schönreden", a:"", pos:"v", en:"to gloss over, to talk up", de:"etwas Schlechtes als gut darstellen", s:"Er versucht, seine Fehler schönzureden.", sec:"A" },
    { w:"faule Ausrede", a:"die", pl:"-n", pos:"n", en:"lame excuse", de:"eine schlechte, unglaubwürdige Ausrede", s:"„Kein Netz“ ist eine faule Ausrede.", sec:"A" },
    { w:"Erwartung", a:"die", pl:"-en", pos:"n", en:"expectation", de:"das, was man von etwas oder jemandem erhofft", s:"Der Film hat meine Erwartungen übertroffen.", sec:"A", c:"eine Erwartung wecken" },
    { w:"in Wahrheit", a:"", pos:"phr", en:"in truth, actually", de:"in Wirklichkeit, tatsächlich", s:"Er wirkte ruhig, in Wahrheit war er sehr nervös.", sec:"A" },
    { w:"Motiv", a:"das", pl:"-e", pos:"n", en:"motive", de:"der Grund, warum jemand etwas tut", s:"Das Motiv für die Lüge war Angst.", sec:"A" },
    { w:"sozial hilfreich", a:"", g:"= prosozial", pos:"adj", en:"prosocial, helpful to others", de:"so, dass es anderen Menschen hilft", s:"Manche Lügen sind sozial hilfreich und schützen andere.", sec:"A" },
    { w:"selbstsüchtig", a:"", g:"= egoistisch", pos:"adj", en:"selfish", de:"nur an den eigenen Vorteil denkend", s:"Eine selbstsüchtige Lüge nützt nur einem selbst.", sec:"A" },
    { w:"Strategie", a:"die", pl:"-n", pos:"n", en:"strategy", de:"ein durchdachter Plan, um ein Ziel zu erreichen", s:"Täuschung ist im Tierreich oft eine Überlebensstrategie.", sec:"A", c:"Überlebensstrategie" },
    { w:"dienen zu", a:"", g:"+ D", pos:"v", en:"to serve (a purpose)", de:"einen bestimmten Zweck haben", s:"Solche Lügen dienen zum Schutz der Gruppe.", sec:"A" },
    { w:"Beziehungen erhalten", a:"", pos:"phr", en:"to maintain relationships", de:"dafür sorgen, dass Beziehungen bestehen bleiben", s:"Kleine Höflichkeitslügen helfen, Beziehungen zu erhalten.", sec:"A" },
    { w:"erleichtern", a:"", pos:"v", en:"to make easier", de:"etwas einfacher machen", s:"Höflichkeit erleichtert den Umgang mit anderen.", sec:"A", c:"den Umgang mit anderen erleichtern" },
    { w:"auswirken, sich positiv auf", a:"", g:"+ A", pos:"v", en:"to have a positive effect on", de:"eine gute Folge für etwas haben", s:"Ehrlichkeit wirkt sich positiv auf das Vertrauen aus.", sec:"A" },
    { w:"Zusammenleben", a:"das", pl:"—", g:"nur Sg.", pos:"n", en:"living together, coexistence", de:"das gemeinsame Leben von Menschen", s:"Regeln erleichtern das Zusammenleben.", sec:"A" },
    { w:"Miteinander", a:"das", pl:"—", g:"nur Sg.", pos:"n", en:"togetherness", de:"das gute, gemeinsame Umgehen miteinander", s:"Ein freundliches Miteinander ist wichtig im Team.", sec:"A" },
    { w:"Interaktion", a:"die", pl:"-en", pos:"n", en:"interaction", de:"das gegenseitige Aufeinander-Reagieren", s:"Sprache steuert unsere soziale Interaktion.", sec:"A" },
    { w:"Harmonie", a:"die", pl:"—", g:"hier nur Sg.", pos:"n", en:"harmony", de:"ein Zustand ohne Streit, in Einklang", s:"Kleine Lügen sollen manchmal die Harmonie bewahren.", sec:"A" },
    { w:"zwischenmenschlich", a:"", pos:"adj", en:"interpersonal", de:"zwischen Menschen, die Beziehungen betreffend", s:"Vertrauen ist die Basis zwischenmenschlicher Beziehungen.", sec:"A" },
    { w:"zurechtkommen mit", a:"", g:"+ D (gut / schlecht)", pos:"v", en:"to cope / get along with", de:"mit etwas oder jemandem gut oder schlecht klarkommen", s:"Mit ehrlicher Kritik komme ich gut zurecht.", sec:"A" },
    { w:"verschaffen, sich", a:"", pos:"v", en:"to obtain, to gain (for oneself)", de:"sich etwas beschaffen oder sichern", s:"Er wollte sich einen unfairen Vorteil verschaffen.", sec:"A", c:"sich einen Vorteil verschaffen" },
    { w:"anrichten", a:"", pos:"v", en:"to cause (damage)", de:"etwas Negatives verursachen", s:"Eine Lüge kann großen Schaden anrichten.", sec:"A", c:"Schaden anrichten" },
    { w:"verheimlichen", a:"", pos:"v", en:"to conceal, to hide", de:"etwas absichtlich nicht sagen oder zeigen", s:"Sie hat ihre Probleme lange verheimlicht.", sec:"A" },
    { w:"Schwäche", a:"die", pl:"-n", pos:"n", en:"weakness", de:"eine Eigenschaft, in der man nicht stark ist", s:"Niemand zeigt gern seine Schwächen.", sec:"A" },
    { w:"abschwächen", a:"", pos:"v", en:"to weaken, to soften", de:"schwächer oder weniger stark machen", s:"Er schwächte seine harte Aussage etwas ab.", sec:"A" },
    { w:"darstellen, sich", a:"", pos:"v", en:"to present (oneself)", de:"sich auf eine bestimmte Weise zeigen", s:"Im Lebenslauf stellt man sich im besten Licht dar.", sec:"A", c:"sich in einem besseren Licht darstellen" },
    { w:"Status", a:"der", pl:"-", pos:"n", en:"status", de:"die Stellung, die jemand in der Gesellschaft hat", s:"Manche lügen, um ihren Status zu erhöhen.", sec:"A" },
    { w:"beschränken, sich auf", a:"", g:"+ A", pos:"v", en:"to limit oneself to", de:"nur bei einer Sache bleiben, nicht mehr tun", s:"Ich beschränke mich auf die wichtigsten Punkte.", sec:"A" },
    { w:"Phänomen", a:"das", pl:"-e", pos:"n", en:"phenomenon", de:"eine auffällige Erscheinung, die man beobachtet", s:"Lügen ist ein weit verbreitetes Phänomen.", sec:"A" },
    { w:"Tierreich", a:"das", pl:"—", g:"nur Sg.", pos:"n", en:"animal kingdom", de:"die gesamte Welt der Tiere", s:"Auch im Tierreich wird viel getäuscht.", sec:"A" },
    { w:"Bemühen", a:"das", pl:"—", g:"nur Sg.", pos:"n", en:"effort, endeavour", de:"der Versuch, sich für etwas anzustrengen", s:"Trotz allen Bemühens gelang die Täuschung nicht.", sec:"A" },
    { w:"verbreitet sein", a:"", pos:"phr", en:"to be widespread", de:"an vielen Stellen oder oft vorkommen", s:"Kleine Lügen sind im Alltag weit verbreitet.", sec:"A" },
    { w:"Übel", a:"das", pl:"-", pos:"n", en:"evil, ill", de:"etwas Schlechtes oder Schädliches", s:"Die Lüge gilt oft als notwendiges Übel.", sec:"A" },
    { w:"lebensnotwendig", a:"", pos:"adj", en:"vital, essential for life", de:"so wichtig, dass man ohne es nicht leben kann", s:"Für manche Tiere ist Tarnung lebensnotwendig.", sec:"A" },
    { w:"Forscher", a:"der", pl:"-", pos:"n", en:"researcher (m)", de:"eine Person, die wissenschaftlich untersucht", s:"Die Forscher beobachteten das Verhalten der Tiere.", sec:"A" },
    { w:"Psychologe", a:"der", pl:"-n", pos:"n", en:"psychologist (m)", de:"ein Fachmann für das Verhalten und Erleben des Menschen", s:"Der Psychologe erklärt, warum wir lügen.", sec:"A", c:"die Psychologin, -nen" },
    { w:"sehen in", a:"", g:"+ D", pos:"v", en:"to see (sth) as / in", de:"etwas als etwas Bestimmtes betrachten", s:"Viele sehen in der Lüge nur etwas Negatives.", sec:"A" },
    { w:"verstehen unter", a:"", g:"+ D", pos:"v", en:"to understand by (a term)", de:"eine bestimmte Bedeutung mit einem Wort verbinden", s:"Was verstehst du unter „Notlüge“?", sec:"A" },
    { w:"begeistert sein von", a:"", g:"+ D", pos:"phr", en:"to be enthusiastic about", de:"etwas ganz toll finden", s:"Die Studierenden waren von dem Experiment begeistert.", sec:"A" },
    // B — Täuschen und Tricksen im Tierreich
    { w:"Trick", a:"der", pl:"-s", pos:"n", en:"trick", de:"ein geschickter Kniff, um ein Ziel zu erreichen", s:"Manche Tiere beherrschen erstaunliche Tricks.", sec:"B", c:"einen Trick beherrschen" },
    { w:"Trickserei", a:"die", pl:"-en", pos:"n", en:"trickery", de:"das ständige Tricksen und Täuschen", s:"Im Tierreich gehört Trickserei zum Überleben.", sec:"B" },
    { w:"vortäuschen", a:"", pos:"v", en:"to feign, to fake", de:"so tun, als ob etwas wäre, was nicht stimmt", s:"Der Vogel täuscht eine Verletzung vor.", sec:"B" },
    { w:"tot stellen, sich", a:"", pos:"v", en:"to play dead", de:"so tun, als wäre man tot", s:"Bei Gefahr stellt sich der Käfer tot.", sec:"B" },
    { w:"anlocken", a:"", pos:"v", en:"to lure, to attract", de:"jemanden oder etwas näher kommen lassen", s:"Mit hellen Farben lockt die Blüte Insekten an.", sec:"B" },
    { w:"weglocken", a:"", pos:"v", en:"to lure away", de:"jemanden von einem Ort weglocken", s:"Die Vogelmutter lockt den Feind vom Nest weg.", sec:"B" },
    { w:"bringen, sich in Gefahr", a:"", pos:"phr", en:"to put (oneself) in danger", de:"sich selbst in eine gefährliche Lage bringen", s:"Um die Jungen zu schützen, bringt sich das Tier in Gefahr.", sec:"B" },
    { w:"Wissenschaftler", a:"der", pl:"-", pos:"n", en:"scientist (m)", de:"eine Person, die Wissenschaft betreibt", s:"Die Wissenschaftler untersuchten das Verhalten der Affen.", sec:"B", c:"die Wissenschaftlerin, -nen" },
    { w:"Biologe", a:"der", pl:"-n", pos:"n", en:"biologist (m)", de:"ein Wissenschaftler, der Lebewesen erforscht", s:"Der Biologe filmte die Tiere in freier Natur.", sec:"B", c:"die Biologin, -nen" },
    { w:"einig sein, sich", a:"", pos:"v", en:"to be in agreement", de:"die gleiche Meinung haben", s:"Die Forscher sind sich einig, dass Tiere täuschen.", sec:"B" },
    { w:"bewusst", a:"", pos:"adj", en:"conscious, deliberate", de:"mit Absicht, nicht zufällig", s:"Manche Tiere täuschen ganz bewusst.", sec:"B" },
    { w:"Beweggrund", a:"der", pl:"¨e", pos:"n", en:"motive, reason", de:"der innere Grund für eine Handlung", s:"Der Beweggrund ist meist der Schutz des Nachwuchses.", sec:"B" },
    { w:"Tendenz", a:"die", pl:"-en", pos:"n", en:"tendency, trend", de:"eine Richtung, in die sich etwas entwickelt", s:"Es gibt eine klare Tendenz zu mehr Tarnung.", sec:"B", c:"die Grundtendenz betrachten" },
    { w:"schützen, sich vor", a:"", g:"+ D", pos:"v", en:"to protect (oneself) from", de:"sich gegen eine Gefahr sichern", s:"Das Tier schützt sich vor Feinden durch Tarnung.", sec:"B" },
    { w:"Schutz", a:"der", pl:"—", g:"nur Sg.", pos:"n", en:"protection", de:"das Sichern gegen eine Gefahr", s:"Die Farben dienen dem Schutz vor Räubern.", sec:"B", c:"Selbstschutz" },
    { w:"Nachwuchs", a:"der", pl:"—", g:"nur Sg.", pos:"n", en:"offspring, young", de:"die Kinder oder Jungtiere", s:"Die Eltern verteidigen ihren Nachwuchs.", sec:"B", c:"= der Nachkomme, -n" },
    { w:"materiell", a:"", pos:"adj", en:"material", de:"die Dinge oder das Geld betreffend", s:"Es geht nicht immer um materielle Vorteile.", sec:"B" },
    { w:"fördern", a:"", pos:"v", en:"to promote, to support", de:"etwas unterstützen und voranbringen", s:"Gute Gene fördern das Überleben der Art.", sec:"B" },
    { w:"Karriere", a:"die", pl:"-n", pos:"n", en:"career", de:"der berufliche Aufstieg eines Menschen", s:"Manche lügen sogar für ihre Karriere.", sec:"B" },
    { w:"Gen", a:"das", pl:"-e", pos:"n", en:"gene", de:"der Träger der Erbinformation", s:"Bestimmte Gene werden an den Nachwuchs weitergegeben.", sec:"B" },
    { w:"Fortpflanzung", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"reproduction", de:"das Bekommen von Nachkommen", s:"Täuschung sichert oft die Fortpflanzung.", sec:"B" },
    { w:"Nest", a:"das", pl:"-er", pos:"n", en:"nest", de:"der Ort, an dem Vögel ihre Jungen aufziehen", s:"Der Vogel lenkt Feinde vom Nest ab.", sec:"B" },
    { w:"Beute", a:"die", pl:"-n", pos:"n", en:"prey, loot", de:"das Tier, das ein Räuber fängt und frisst", s:"Der Fuchs schleicht sich an seine Beute heran.", sec:"B" },
    { w:"Tier", a:"das", pl:"-e", pos:"n", en:"animal", de:"ein Lebewesen, das kein Mensch und keine Pflanze ist", s:"Viele Tiere tarnen sich vor Feinden.", sec:"B", c:"Säugetier, Raubtier" },
    { w:"Hahn", a:"der", pl:"¨e", pos:"n", en:"rooster, cock", de:"das männliche Huhn", s:"Der Hahn kräht am frühen Morgen.", sec:"B" },
    { w:"Henne", a:"die", pl:"-n", pos:"n", en:"hen", de:"das weibliche Huhn", s:"Die Henne beschützt ihre Küken.", sec:"B" },
    { w:"Futter", a:"das", pl:"—", g:"nur Sg.", pos:"n", en:"feed, (animal) food", de:"das Essen für Tiere", s:"Der Hahn ruft die Hennen zum Futter.", sec:"B" },
    { w:"fressen", a:"", pos:"v", en:"to eat (of animals)", de:"essen, wenn ein Tier es tut", s:"Raubtiere fressen andere Tiere.", sec:"B" },
    { w:"Feind", a:"der", pl:"-e", pos:"n", en:"enemy", de:"jemand oder etwas, das einem schaden will", s:"Der Hase flieht vor seinem Feind.", sec:"B", c:"Fressfeind" },
    { w:"leblos", a:"", pos:"adj", en:"lifeless", de:"ohne Leben, wie tot", s:"Der Käfer wirkt völlig leblos.", sec:"B" },
    { w:"Revier", a:"das", pl:"-e", pos:"n", en:"territory", de:"das Gebiet, in dem ein Tier lebt", s:"Das Männchen verteidigt sein Revier.", sec:"B" },
    { w:"verteidigen", a:"", pos:"v", en:"to defend", de:"etwas gegen einen Angriff schützen", s:"Die Tiere verteidigen ihr Nest energisch.", sec:"B" },
    { w:"Geschrei", a:"das", pl:"—", g:"nur Sg.", pos:"n", en:"screaming, clamour", de:"lautes, andauerndes Schreien", s:"Mit lautem Geschrei vertreibt der Vogel Feinde.", sec:"B" },
    { w:"Gebrüll", a:"das", pl:"—", g:"nur Sg.", pos:"n", en:"roaring", de:"das laute Brüllen von Tieren", s:"Das Gebrüll des Löwen schreckt Feinde ab.", sec:"B" },
    { w:"abschrecken", a:"", pos:"v", en:"to deter, to scare off", de:"jemanden durch Angst fernhalten", s:"Grelle Farben sollen Feinde abschrecken.", sec:"B" },
    { w:"Abschreckung", a:"die", pl:"-en", pos:"n", en:"deterrence", de:"das Fernhalten durch Drohung oder Angst", s:"Die Farben dienen der Abschreckung.", sec:"B" },
    { w:"verbergen, sich", a:"", pos:"v", en:"to hide, to conceal", de:"sich oder etwas unsichtbar machen", s:"Das Tier verbirgt sich im hohen Gras.", sec:"B" },
    // C — Vorsicht Täuschung!
    { w:"Beschwerde", a:"die", pl:"-n", pos:"n", en:"complaint", de:"eine Meldung, dass man mit etwas unzufrieden ist", s:"Ich habe eine Beschwerde an den Shop geschickt.", sec:"C" },
    { w:"Werbeanzeige", a:"die", pl:"-n", pos:"n", en:"advertisement", de:"eine bezahlte Anzeige, die etwas bewirbt", s:"Die Werbeanzeige versprach mehr, als das Produkt hielt.", sec:"C" },
    { w:"Lieferumfang", a:"der", pl:"¨e", pos:"n", en:"scope of delivery, what's included", de:"alles, was mit einer Ware mitgeliefert wird", s:"Das Kabel gehört nicht zum Lieferumfang.", sec:"C" },
    { w:"Adapter", a:"der", pl:"-", pos:"n", en:"adapter", de:"ein Teil, das zwei Geräte verbindet", s:"Für die Kamera brauche ich noch einen Adapter.", sec:"C" },
    { w:"Anleitung", a:"die", pl:"-en", pos:"n", en:"instructions, manual", de:"ein Text, der erklärt, wie etwas funktioniert", s:"In der Anleitung steht, wie man das Gerät einstellt.", sec:"C", c:"Bedienungsanleitung" },
    { w:"Kabel", a:"das", pl:"-", pos:"n", en:"cable", de:"eine Leitung für Strom oder Daten", s:"Das USB-Kabel fehlte in der Verpackung.", sec:"C" },
    { w:"Objektiv", a:"das", pl:"-e", pos:"n", en:"(camera) lens", de:"der Teil der Kamera, durch den man fotografiert", s:"Das Objektiv war leider beschädigt.", sec:"C" },
    { w:"Ausstattung", a:"die", pl:"-en", pos:"n", en:"equipment, features", de:"alles, was zu einem Gerät oder Raum gehört", s:"Die Ausstattung des Handys ist sehr gut.", sec:"C" },
    { w:"Zubehör", a:"das", pl:"—", g:"meist Sg.", pos:"n", en:"accessories", de:"zusätzliche Teile, die zu einem Gerät passen", s:"Das Zubehör muss man extra kaufen.", sec:"C" },
    { w:"fehlend", a:"", pos:"adj", en:"missing", de:"nicht da, obwohl es da sein sollte", s:"Wegen des fehlenden Kabels schrieb ich eine Beschwerde.", sec:"C" },
    { w:"Kreativität", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"creativity", de:"die Fähigkeit, Neues und Fantasievolles zu schaffen", s:"Werbung lebt von Kreativität.", sec:"C" },
    { w:"Bestätigung", a:"die", pl:"-en", pos:"n", en:"confirmation", de:"eine Nachricht, dass etwas in Ordnung ist", s:"Nach dem Kauf kam eine Bestätigung per E-Mail.", sec:"C", c:"die Bestellbestätigung" },
    { w:"eintreffen bei", a:"", g:"+ D", pos:"v", en:"to arrive (at)", de:"an einem Ort ankommen", s:"Das Paket ist gestern bei mir eingetroffen.", sec:"C" },
    { w:"zur Verfügung stellen", a:"", pos:"phr", en:"to make available, to provide", de:"etwas zum Benutzen geben", s:"Der Händler stellt ein Ersatzgerät zur Verfügung.", sec:"C" },
    { w:"beifügen", a:"", pos:"v", en:"to enclose, to attach", de:"etwas zusätzlich dazulegen", s:"Bitte fügen Sie die Rechnung der Sendung bei.", sec:"C" },
    { w:"zusenden", a:"", pos:"v", en:"to send (to sb)", de:"jemandem etwas per Post schicken", s:"Man wird mir das fehlende Teil kostenlos zusenden.", sec:"C" },
    { w:"portofrei", a:"", pos:"adj", en:"postage-free", de:"ohne Kosten für den Versand", s:"Die Rücksendung ist für mich portofrei.", sec:"C" },
    { w:"einer Forderung nachkommen", a:"", pos:"phr", en:"to comply with a demand", de:"tun, was jemand verlangt", s:"Der Shop kam meiner Forderung nach und erstattete das Geld.", sec:"C" },
    { w:"widerrufen", a:"", pos:"v", en:"to revoke, to cancel", de:"einen Vertrag oder Kauf offiziell rückgängig machen", s:"Ich habe den Kauf innerhalb von 14 Tagen widerrufen.", sec:"C" },
    { w:"Widerruf", a:"der", pl:"-e", pos:"n", en:"revocation, cancellation", de:"das Rückgängigmachen eines Vertrags", s:"Der Widerruf muss schriftlich erfolgen.", sec:"C" },
    { w:"Betrag", a:"der", pl:"¨e", pos:"n", en:"amount, sum", de:"eine bestimmte Menge Geld", s:"Der Betrag wurde mir zurückgebucht.", sec:"C" },
    { w:"zurückbuchen", a:"", pos:"v", en:"to refund, to charge back", de:"Geld auf ein Konto zurückzahlen", s:"Die Bank hat den Betrag zurückgebucht.", sec:"C" },
    { w:"Rücksendung", a:"die", pl:"-en", pos:"n", en:"return (of goods)", de:"das Zurückschicken einer Ware", s:"Die Rücksendung ist kostenlos.", sec:"C" },
    { w:"Zoll", a:"der", pl:"¨e", pos:"n", en:"customs (duty)", de:"die Gebühr für Waren aus dem Ausland", s:"Für das Paket aus den USA musste ich Zoll zahlen.", sec:"C" },
    { w:"Zusatzkosten", a:"die", pl:"", g:"nur Pl.", pos:"n", en:"additional costs", de:"Kosten, die zusätzlich dazukommen", s:"Es entstanden unerwartete Zusatzkosten.", sec:"C" },
    // D — Also mal ganz ehrlich!
    { w:"Schaubild", a:"das", pl:"-er", pos:"n", en:"diagram, chart", de:"eine Grafik, die Zahlen anschaulich zeigt", s:"Das Schaubild zeigt, wie oft Menschen lügen.", sec:"D" },
    { w:"Grafik", a:"die", pl:"-en", pos:"n", en:"graphic, chart", de:"eine bildliche Darstellung von Daten", s:"Die Grafik macht die Ergebnisse leicht verständlich.", sec:"D" },
    { w:"auswerten", a:"", pos:"v", en:"to evaluate, to analyse", de:"Daten untersuchen und Schlüsse ziehen", s:"Die Forscher werteten die Umfrage aus.", sec:"D" },
    { w:"betrachten", a:"", pos:"v", en:"to look at, to consider", de:"sich etwas genau ansehen", s:"Betrachten wir die Zahlen einmal genauer.", sec:"D" },
    { w:"Umfrage", a:"die", pl:"-n", pos:"n", en:"survey", de:"eine Befragung vieler Menschen zu einem Thema", s:"Laut der Umfrage lügt fast jeder gelegentlich.", sec:"D" },
    { w:"repräsentativ", a:"", pos:"adj", en:"representative", de:"typisch für eine ganze Gruppe", s:"Die Studie ist für die Bevölkerung repräsentativ.", sec:"D" },
    { w:"auffällig", a:"", pos:"adj", en:"striking, conspicuous", de:"so, dass es sofort ins Auge fällt", s:"Auffällig ist, dass Männer öfter übertreiben.", sec:"D" },
    { w:"Proband", a:"der", pl:"-en", pos:"n", en:"test subject, participant", de:"eine Person, die an einem Test teilnimmt", s:"Die Probanden füllten einen Fragebogen aus.", sec:"D" },
    { w:"befragen", a:"", pos:"v", en:"to survey, to question", de:"jemandem Fragen zu einem Thema stellen", s:"Man befragte tausend Personen zum Thema Ehrlichkeit.", sec:"D" },
    { w:"Ehrlichkeit", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"honesty", de:"die Eigenschaft, die Wahrheit zu sagen", s:"Ehrlichkeit schafft Vertrauen.", sec:"D" },
    { w:"ehrlich", a:"", g:"≠ unehrlich", pos:"adj", en:"honest", de:"die Wahrheit sagend, aufrichtig", s:"Sei ehrlich: Hat dir das Essen geschmeckt?", sec:"D" },
    { w:"übertreiben", a:"", pos:"v", en:"to exaggerate", de:"etwas größer oder schlimmer darstellen, als es ist", s:"Beim Erzählen übertreibt er gern.", sec:"D" },
    { w:"aufmuntern", a:"", pos:"v", en:"to cheer up", de:"jemandem bessere Laune machen", s:"Ein kleines Kompliment kann jemanden aufmuntern.", sec:"D" },
    { w:"Freude bereiten", a:"", pos:"phr", en:"to bring joy", de:"jemanden glücklich machen", s:"Mit einer kleinen Notlüge wollte er ihr eine Freude bereiten.", sec:"D" },
    { w:"Fleiß", a:"der", pl:"—", g:"nur Sg.", pos:"n", en:"diligence", de:"das fleißige, ausdauernde Arbeiten", s:"Mit Fleiß erreicht man mehr als mit Tricks.", sec:"D" },
    { w:"Engagement", a:"das", pl:"—", g:"hier nur Sg.", pos:"n", en:"commitment, dedication", de:"der starke Einsatz für eine Sache", s:"Ihr Engagement für das Projekt war groß.", sec:"D" },
    { w:"vermeiden", a:"", pos:"v", en:"to avoid", de:"etwas nicht tun oder nicht geschehen lassen", s:"Ehrliche Menschen vermeiden Ausreden.", sec:"D" },
    { w:"in Ruhe lassen", a:"", pos:"phr", en:"to leave (sb) alone", de:"jemanden nicht stören", s:"Lass mich bitte kurz in Ruhe.", sec:"D" },
    { w:"Trost spenden", a:"", pos:"phr", en:"to give comfort", de:"jemanden in einer schweren Zeit trösten", s:"Manchmal spendet eine kleine Lüge Trost.", sec:"D" },
    { w:"ausgeben etw. als", a:"", pos:"phr", en:"to pass sth off as", de:"etwas fälschlich als etwas anderes darstellen", s:"Er gibt fremde Ideen als eigene aus.", sec:"D" },
    { w:"Lebenslüge", a:"die", pl:"-n", pos:"n", en:"life lie, self-deception", de:"eine große Lüge, mit der jemand jahrelang lebt", s:"Seine Lebenslüge war, dass er alles allein geschafft habe.", sec:"D" },
    { w:"bestehen", a:"", pos:"v", en:"to exist", de:"vorhanden sein, existieren", s:"Zwischen den beiden besteht eine enge Beziehung.", sec:"D", c:"es besteht eine Beziehung" },
    { w:"Bekanntenkreis", a:"der", pl:"-e", pos:"n", en:"circle of acquaintances", de:"die Menschen, die man kennt", s:"In meinem Bekanntenkreis lügt kaum jemand.", sec:"D" },
    { w:"Körpersprache", a:"die", pl:"—", g:"nur Sg.", pos:"n", en:"body language", de:"das, was man mit Gesten und Haltung ausdrückt", s:"An der Körpersprache erkennt man oft eine Lüge.", sec:"D" },
    { w:"eine Rolle spielen", a:"", pos:"phr", en:"to play a role, to matter", de:"wichtig oder von Bedeutung sein", s:"Vertrauen spielt in Freundschaften eine große Rolle.", sec:"D" }
  ]
};
