/* Tier 0 visuals: word -> emoji anchor, shown on the BACK of the card.
   Keyed by the exact `w` in the deck. Abstract words are intentionally omitted
   (no emoji is better than a misleading one). Duplicate words across lessons
   share one emoji that fits every sense. */
window.EMOJI = {
  // ---- Lektion 1 ----
  "Stoff":"📚","durchdenken":"🤔","zusammenfassen":"📋","konzentrieren, sich auf":"🎯",
  "ordnen nach":"🗂️","aufschreiben":"✍️","achten auf":"👀","nachsprechen":"🗣️","anwenden":"🛠️",
  "bewegen, sich":"🏃","Sprachkenntnisse":"💬","Aussage":"🗨️","zustimmen":"👍","Widerspruch":"🙅",
  "Ansicht":"💭","Forum":"💬","Beitrag":"📝","Vorbereitung":"📋","Vorschlag":"💡","Alternative":"🔀",
  "Lerntechnik":"🎓","Lernmethode":"📘","Lerngruppe":"👥","Lernplan":"🗓️","Lernstil":"🎨",
  "Lerntipp":"💡","Lernerfahrung":"🎓","Lerntyp":"🧑‍🎓","Methodenmix":"🎛️","auditiv":"👂","visuell":"👁️",
  "veraltet":"🕰️","Studie":"🔬","Rangfolge":"📊","bewerten":"⭐","abschneiden":"📊","überprüfen":"🔍",
  "empfehlenswert":"👍","hilfreich":"🤝","effektiv":"⚡","optimal":"💯","gegenteilig":"↔️",
  "hervorheben":"🖍️","markieren":"🖍️","unterstreichen":"✏️","Vorwissen":"🧠","Überblick":"🗺️",
  "überfliegen":"👓","global":"🌐","selektiv":"🔍","Kerninformation":"🔑","nachdenken über":"🤔",
  "Zusammenhang":"🔗","wiedergeben":"🔁","abfragen":"❓","behalten":"🧠","Gedächtnis":"🧠",
  "Sinnesorgan":"👂","verknüpfen mit":"🔗","aufteilen":"➗","regelmäßig":"🔁","abhaken":"☑️",
  "Erfolgserlebnis":"🎉","beherrschen":"💪","aufschieben":"⏳","ängstlich":"😰","Behauptung":"🗨️",
  "Zeitalter":"⏳","Forschung":"🔬","Neurowissenschaft":"🧠","Rückgang":"📉","Ergonomie":"🪑",
  "Motorik":"✋","Schrift":"🔤","Schreiben mit der Hand":"✍️","Handschreiben":"✍️","flüssig":"🖋️",
  "lehren":"👩‍🏫","Erlernen":"🎓","Abschaffung":"🚫","abschaffen":"🚫","Tastatur":"⌨️","tippen":"⌨️",
  "Tippen":"⌨️","Wirkung":"💥","Gehirn":"🧠","Gehirnaktivität":"🧠","Gehirnareal":"🧠","Bereich":"📍",
  "aktivieren":"⚡","wiedererkennen":"🔁","erinnern, sich an":"💭","Verknüpfung":"🔗","Verbindung":"🔗",
  "Speicher":"💾","extern":"🔌","verarbeiten":"⚙️","Gehörte":"👂","merken, sich":"🧠","Notiz":"📝",
  "Notizblock":"📓","notieren":"✍️","Vorlesung":"🎓","mitschreiben":"✍️","protokollieren":"📋",
  "Ergebnis":"✅","Inhalt":"📄","intensiv":"🔥","dauerhaft":"♾️","Ausführung":"🔧","Wissen":"🧠",
  "Fakt":"✅","Grundlage":"🧱","beitragen zu":"🤝","Diskussion":"💬","fleißig":"🐜",
  "Kommunikationsfähigkeit":"💬","Arbeitsweise":"🧑‍💻","Zeitmanagement":"⏱️","Einzelarbeit":"🧍",
  "Gruppenarbeit":"👥","ermöglichen":"🔓","Stellungnahme":"🗨️","Einleitung":"📖","Hauptteil":"📄",
  "Schluss":"🏁","Fazit":"🎯","Argument":"💬","These":"💡","Vorteil":"➕","Nachteil":"➖",
  // ---- Lektion 2 ----
  "Architektur":"🏛️","Architekt":"👷","Architektin":"👷‍♀️","Stadtplanung":"🗺️","Hochhaus":"🏢",
  "Wolkenkratzer":"🏙️","Skyline":"🌆","Altstadt":"🏘️","historisch":"🏛️","Run":"🏃","Verstädterung":"🏙️",
  "Landflucht":"🚜","Prognose":"🔮","prognostizieren":"🔮","weltweit":"🌍","Anteil":"🥧","verdoppeln":"✖️",
  "Attraktivität":"✨","attraktiv":"✨","anregend":"💫","Image":"🖼️","cool":"😎","Bildungseinrichtung":"🏫",
  "Arbeitsstelle":"💼","Startup":"🚀","Umfrage":"📊","Faktor":"🧩","Lärm":"🔊","Verschmutzung":"🏭",
  "Smog":"🌫️","Abgas":"💨","schädigen":"⚠️","Viertel":"🏘️","blicken":"👀","Technologie":"💻",
  "Technologiefirma":"🏢","Digitalisierung":"💻","digital":"💻","vernetzen":"🔗","Workshop":"🛠️",
  "innovativ":"💡","lebenswert":"🌳","Konzept":"💡","gründen":"🚀","anbauen":"🌱","Anbau":"🌱",
  "versorgen":"🤲","Landschaft":"🏞️","Landwirtschaft":"🚜","landwirtschaftlich":"🚜","vertikal":"↕️",
  "beitragen":"🤝","Etage":"🏢","-stöckig":"🏢","preisgünstig":"💸","Fläche":"🟩","Fußballfeld":"⚽",
  "Ersatz":"🔁","Sonnenlicht":"☀️","beleuchten":"💡","Beleuchtung":"💡","urban":"🏙️","Trend":"📈",
  "gärtnern":"🌱","begrünen":"🌿","pflanzen":"🌱","Pflanze":"🪴","säen":"🌾","Samen":"🌰","Ernte":"🌾",
  "ernten":"🧺","gießen":"💧","genießen":"😌","Wachstum":"📈","Parkgarage":"🅿️","Dachterrasse":"🏙️",
  "Innenhof":"🏛️","trist":"☁️","Biene":"🐝","Vordergrund":"🔍","brachliegen":"🏜️","bearbeiten":"🛠️",
  "erwerben":"🛒","Bewirtschaftung":"🚜","verwalten":"🗂️","jährlich":"📅","Betrag":"💶",
  "austauschen, sich":"🔄","gegenseitig helfen, sich":"🤝","anonym":"🕶️","Anonymität":"🕶️","Mittel":"🔧",
  "Nachbarschaft":"🏘️","aufbauen":"🏗️","verringern":"📉","wirken":"🎭","altmodisch":"🕰️",
  "verschlossen":"🔒","Gebäude":"🏢","abreißen":"🔨","Abriss":"🔨","Quadratmeter":"📐","umweltschonend":"♻️",
  "umbauen":"🏗️","Umbau":"🏗️","komplett":"✅","Fassade":"🏛️","Ebene":"📶","horizontal":"↔️",
  "Panorama":"🏞️","wohlfühlen, sich":"😌","Entwicklung":"📈","eingehen auf":"🔍","kommen zu":"➡️",
  // ---- Lektion 3 ----
  "Lüge":"🤥","Betrug":"🎭","betrügen":"🎭","flunkern":"🤥","schwindeln":"🤥","schummeln":"🃏",
  "tricksen":"🃏","Irreführung":"🌀","Täuschung":"🎭","täuschen":"🎭","Fake News":"📰","manipulieren":"🎛️",
  "fälschen":"✒️","Plagiat":"📋","Doping":"💉","Halbwahrheit":"⚖️","Beschönigung":"💄","schönreden":"💄",
  "faule Ausrede":"🙄","Erwartung":"🤞","Motiv":"🎯","Strategie":"♟️","Interaktion":"🔄","Harmonie":"☯️",
  "verschaffen, sich":"🤲","anrichten":"💥","verheimlichen":"🙊","Schwäche":"🩹","darstellen, sich":"🎭",
  "Status":"🏷️","Phänomen":"✨","Tierreich":"🦁","verbreitet sein":"🌍","Übel":"👿","lebensnotwendig":"❤️",
  "Forscher":"🔬","Psychologe":"🧠","Trick":"🎩","Trickserei":"🎩","vortäuschen":"🎭",
  "tot stellen, sich":"💀","anlocken":"🎣","weglocken":"🎣","bringen, sich in Gefahr":"⚠️",
  "Wissenschaftler":"🔬","Biologe":"🧬","bewusst":"🧠","Beweggrund":"🎯","Tendenz":"📈",
  "schützen, sich vor":"🛡️","Schutz":"🛡️","Nachwuchs":"🐣","materiell":"💰","fördern":"📈","Karriere":"📈",
  "Gen":"🧬","Fortpflanzung":"🐣","Nest":"🪹","Beute":"🍖","Tier":"🐾","Hahn":"🐓","Henne":"🐔",
  "Futter":"🌾","fressen":"🍖","Feind":"⚔️","leblos":"💀","Revier":"🗺️","verteidigen":"🛡️",
  "Geschrei":"📢","Gebrüll":"🦁","abschrecken":"😱","Abschreckung":"⚠️","verbergen, sich":"🫥",
  "Beschwerde":"📣","Werbeanzeige":"📢","Lieferumfang":"📦","Adapter":"🔌","Anleitung":"📖","Kabel":"🔌",
  "Objektiv":"📷","Ausstattung":"🧰","Zubehör":"🧰","fehlend":"❓","Kreativität":"🎨","Bestätigung":"✅",
  "zusenden":"📮","portofrei":"📮","widerrufen":"↩️","Widerruf":"↩️","zurückbuchen":"💳","Rücksendung":"📦",
  "Zoll":"🛃","Zusatzkosten":"💸","Schaubild":"📊","Grafik":"📈","auswerten":"📊","betrachten":"🔍",
  "repräsentativ":"📊","auffällig":"🚩","Proband":"🧑‍🔬","befragen":"❓","Ehrlichkeit":"🤝","ehrlich":"🤝",
  "übertreiben":"🎭","aufmuntern":"🌈","Freude bereiten":"🎁","Fleiß":"🐜","Engagement":"💪","vermeiden":"🚫",
  "Trost spenden":"🤗","Lebenslüge":"🤥","Bekanntenkreis":"👥","Körpersprache":"🙆","eintreffen bei":"📦",
  "beifügen":"📎","zum Schutz beitragen":"🛡️",
  // ---- Lektion 4 ----
  "Aspekt":"🔷","Beratung":"💬","Komfort":"🛋️","Isolation":"🏝️","Verfügbarkeit":"🟢","Serie":"📺",
  "online":"🌐","Online-Banking":"🏦","bloggen":"✍️","chatten":"💬","posten":"📮","simsen":"📱",
  "skypen":"📹","streamen":"📺","twittern":"🐦","whatsappen":"💬","App":"📱","Telemedizin":"🩺",
  "E-Health":"🩺","Telekommunikation":"📡","Vernetzung":"🔗","Austausch":"🔄","Datenübermittlung":"📡",
  "Videochat":"📹","mobil":"📱","Nutzen":"💡","Einsatz":"🚀","Anwendung":"📲","Erkrankung":"🤒",
  "Symptom":"🌡️","Diagnose":"🩺","Diagnostik":"🔬","Einschätzung":"📊","einschätzen":"📊","Therapie":"💊",
  "Behandlung":"🩹","Distanz":"📏","Zweitmeinung":"🩺","Spezialist":"🧑‍⚕️","ärztlich":"⚕️","aufsuchen":"🏥",
  "konsultieren":"🩺","ersetzen":"🔁","reduzieren":"📉","ländlich":"🌾","Notfall":"🚨","Rettungswagen":"🚑",
  "Ambulanz":"🏥","Wartebereich":"⏳","Wartezeit":"⏳","gesetzlich":"⚖️","Privatsphäre":"🔒",
  "Infrastruktur":"🏗️","Akte":"🗂️","Finanzen":"💰","Diebstahl":"🕵️","Manipulation":"🎛️","Missbrauch":"⚠️",
  "kritisieren":"👎","einführen":"🆕","sinnvoll":"👍","Plattform":"🌐","Event":"🎪","Veranstaltung":"🎪",
  "Tagung":"🎤","Meeting":"👥","Location":"📍","Buchung":"📅","Messe":"🏢","Präsentation":"📊",
  "präsentieren":"📊","Geschäftsidee":"💡","Hintergrund":"🖼️","Gründung":"🚀","Gründer":"🧑‍💼",
  "Bewirtung":"🍽️","recherchieren":"🔍","zeitintensiv":"⏳","Service":"🛎️","auswählen":"✅","passend":"🧩",
  "Privatperson":"🧍","erweitern":"➕","ausweiten":"↔️","ausbauen":"🏗️","Ausbau":"🏗️","expandieren":"🌍",
  "Catering":"🍽️","Dienstleister":"🛠️","Suche":"🔍","engagiert":"💪","mitgestalten":"🎨","Sales-Team":"🧑‍💼",
  "Bestandskunde":"🤝","Marketing":"📣","Bekanntheit":"⭐","Internetpräsenz":"🌐","Zielgruppe":"🎯",
  "motivieren":"🔥","erfolgreich":"🏆","Smart Home":"🏠","smart":"🤖","Smartphone":"📱","steuern":"🎛️",
  "kontrollieren":"🔍","überwachen":"📹","Überwachung":"📹","Sensor":"📡","Verbrauch":"🔋","Einsparung":"💰",
  "Einbruch":"🦹","Einbrecher":"🦹","Brand":"🔥","Nutzung":"📲","hinterlassen":"👣","hacken":"💻",
  "missbrauchen":"⚠️","Anschaffung":"🛒","Bequemlichkeit":"🛋️","bedenken":"🤔","Argumentation":"💬",
  "Steuerung":"🎛️","senken":"📉","Tablet":"📱","umweltbewusst":"♻️"
};
